<!DOCTYPE HTML>
<html lang="En" class="sidebar-visible no-js navy">
    <head>
        <!-- Book generated using mdBook -->
        <meta charset="UTF-8">
        <title>005 - Paraphrasing the Pdfs</title>


        <!-- Custom HTML head -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css" integrity="sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc" crossorigin="anonymous">
        
        <link rel="stylesheet" href="css/tavianator.css">
        
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js" integrity="sha384-YNHdsYkH6gMx9y3mRkmcJ2mFUjTd0qNQQvY9VYZgQd7DcN7env35GzlmFaZ23JGp" crossorigin="anonymous"></script>
        
        <script src="tavianator.js"></script>
        
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-EBDQXGZ6R1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-EBDQXGZ6R1');
        </script>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        <link rel="icon" href="favicon.svg">
        <link rel="shortcut icon" href="favicon.png">
        <link rel="stylesheet" href="css/variables.css">
        <link rel="stylesheet" href="css/general.css">
        <link rel="stylesheet" href="css/chrome.css">
        <link rel="stylesheet" href="css/print.css" media="print">

        <!-- Fonts -->
        <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
        <link rel="stylesheet" href="fonts/fonts.css">

        <!-- Highlight.js Stylesheets -->
        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme stylesheets -->
        <link rel="stylesheet" href="./theme/tabbed-code-blocks.css">

    </head>
    <body>
    <div id="body-container">
        <!-- Provide site root to javascript -->
        <script>
            var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "navy";
        </script>

        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script>
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script>
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('navy')
            html.classList.add(theme);
            html.classList.add('js');
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script>
            var html = document.querySelector('html');
            var sidebar = null;
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            } else {
                sidebar = 'hidden';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <div class="sidebar-scrollbox">
                <ol class="chapter"><li class="chapter-item expanded "><a href="index.html"><strong aria-hidden="true">1.</strong> INTRODUCTION</a></li><li class="chapter-item expanded "><a href="mediacal_summilation.html"><strong aria-hidden="true">2.</strong> medical_similation1</a></li><li class="chapter-item expanded "><a href="sim_medical.html"><strong aria-hidden="true">3.</strong> medical similation2</a></li><li class="chapter-item expanded "><a href="2.html"><strong aria-hidden="true">4.</strong> 2</a></li><li class="chapter-item expanded "><a href="2-07h08.html"><strong aria-hidden="true">5.</strong> 2-07h08</a></li><li class="chapter-item expanded "><a href="2-11h00.html"><strong aria-hidden="true">6.</strong> 2-11h00</a></li><li class="chapter-item expanded "><a href="004.html"><strong aria-hidden="true">7.</strong> 004</a></li><li class="chapter-item expanded "><a href="005.html" class="active"><strong aria-hidden="true">8.</strong> 005</a></li><li class="chapter-item expanded "><a href="006.html"><strong aria-hidden="true">9.</strong> 006</a></li></ol>
            </div>
            <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
        </nav>

        <!-- Track and set sidebar scroll position -->
        <script>
            var sidebarScrollbox = document.querySelector('#sidebar .sidebar-scrollbox');
            sidebarScrollbox.addEventListener('click', function(e) {
                if (e.target.tagName === 'A') {
                    sessionStorage.setItem('sidebar-scroll', sidebarScrollbox.scrollTop);
                }
            }, { passive: true });
            var sidebarScrollTop = sessionStorage.getItem('sidebar-scroll');
            sessionStorage.removeItem('sidebar-scroll');
            if (sidebarScrollTop) {
                // preserve sidebar scroll position when navigating via links within sidebar
                sidebarScrollbox.scrollTop = sidebarScrollTop;
            } else {
                // scroll sidebar to current active section when navigating via "next/previous chapter" buttons
                var activeSection = document.querySelector('#sidebar .active');
                if (activeSection) {
                    activeSection.scrollIntoView({ block: 'center' });
                }
            }
        </script>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                                <div id="menu-bar-hover-placeholder"></div>
                <div id="menu-bar" class="menu-bar sticky">
                    <div class="left-buttons">
                        <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                            <i class="fa fa-bars"></i>
                        </button>
                        <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                            <i class="fa fa-paint-brush"></i>
                        </button>
                        <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                            <li role="none"><button role="menuitem" class="theme" id="light">Light</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="rust">Rust</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button></li>
                        </ul>
                        <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>

                    <h1 class="menu-title">Paraphrasing the Pdfs</h1>

                    <div class="right-buttons">
                        <a href="print.html" title="Print this book" aria-label="Print this book">
                            <i id="print-button" class="fa fa-print"></i>
                        </a>
                        <a href="https://github.com/ayoubelmhamdi/pdfgpt" title="Git repository" aria-label="Git repository">
                            <i id="git-repository-button" class="fa fa-github"></i>
                        </a>
                        <a href="https://github.com/ayoubelmhamdi/pdfgpt/tree/master/src/005.md" title="Suggest an edit" aria-label="Suggest an edit">
                            <i id="git-edit-button" class="fa fa-edit"></i>
                        </a>

                    </div>
                </div>

                <div id="search-wrapper" class="hidden">
                    <form id="searchbar-outer" class="searchbar-outer">
                        <input type="search" id="searchbar" name="searchbar" placeholder="Search this book ..." aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                    </form>
                    <div id="searchresults-outer" class="searchresults-outer hidden">
                        <div id="searchresults-header" class="searchresults-header"></div>
                        <ul id="searchresults">
                        </ul>
                    </div>
                </div>

                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script>
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
<h2 id="abstract"><a class="header" href="#abstract">Abstract</a></h2>
<p>Les méthodes de simulations par Monte Carlo consistent a simuler la réalite , elle sont des
algorithmes visant a résoudre des problémes complexes dans divers domaines.Ces méthodes
reposent sur I’échantillonnage de nombres aléatoires générés par un générateur spécifique.
Dans ce mémoire nous exploitons cette propriété pour aborder le transport des ions dans
I'eau afin de déterminer leurs caractéristiques balistiques en utilisant le code PHITS .
La distribution de la dose en profondeur caractérisée par le pic de Bragg et la faible
pénombre latérale des ions par rapport aux photons et aux électrons, 'efficacité en fin de
parcours des ions carbone est supérieure a celle des protons et des autres ions lourds et un
dépot modéré de dose en avant et aprés le pic rendent les ions carbone favorable en théra-
pie tumorale notamment les tumeurs radio-résistantes qui sont proches d’organes a risque y
compris les tumeurs : cérébrales, de la téte et de cou, pédiatrique, prostate , oculaire ...</p>
<h2 id="abstract-1"><a class="header" href="#abstract-1">Abstract</a></h2>
<p>Monte Carlo simulation methods consist of simulating reality, they are algorithms aimed at
solving complex problems in various fields. These methods are based on sampling random
numbers generated by a specific generator. In this thesis we exploit this property to address
the transport of ions in water to determine their ballistic characteristics using the PHITS
code. The depth dose distribution characterized by the Bragg peak and the low lateral pe-
numbra of the ions compared to photons and electrons, the efficiency at the end of the path
of carbon ions is higher than that of protons and other heavy ions and a moderate dose de-
position forward and after the peak make carbon ions favorable in tumor therapy including
radio-resistant tumors that are close to organs with Risk including tumors : cerebral, head
and neck, pediatric, prostate, eye...</p>
<h1 id="introduction-generale"><a class="header" href="#introduction-generale">INTRODUCTION GENERALE</a></h1>
<p>La simulation est une technique consiste &amp; modéliser des phénomenes réels, elle permet
de calculer sur un ordinateur les solutions des modéles mathématique donc simuler la réalité
physique, de représenter le fonctionnement d’'un systéme composé de différents centres d’ac-
tivités, de mettre en évidence les caractéristiques de ceux-ci et les interactions entre eux, de
décrire la circulation des différents objets traités par ces processus, et en fin d’observer le
comportement d'un systéme dans son ensemble et son évolution dans le temps.
La simulation par la méthode de Monte Carlo?! spécifient une famille de méthodes algo-
rithmiques permettant de calculer des valeurs numeériques approchées a 'aide de processus
stochastiques, c’est-a-dire des techniques probabilistes .La méthode de Monte Carlo a été
spécialement développée pour les besoins du projet Manhattan pendant la Seconde Guerre
mondiale a la suite de recherches sur la fabrication de bombes atomiques [1]. Ces méthodes
sont particulierement utiles en informatique intégrale et en physique des particules, ou les
simulations probabilistes peuvent estimer la forme d’un signal ou la sensibilité d'un détecteur
[2].
Généralement les méthodes de Monte Carlo sont utilisées pour résoudre des problémes
mathématiques et physiques complexes [3] qui ne peuvent pas étre résolus par des méthodes
analytiques telles que la résolution de I’équation de Boltzmann 2. Elles sont appliquées dans
plusieurs domaines par exemple en physique, chimie, biologie, statistiques, etc. Leur applica-
tions s’étendent a la radioprotection et la physique médicale a raison de la nature stochastique
des processus physiques tels que le transport des particules et les interactions rayonnements-
maticre [4]. Les lois de probabilité régissant ces différents processus sont bien connues : par</p>
<ol>
<li>Monte Carlo : Est une région a Monaco,France qui est reconnue par un casino d’ou le caractére
probabiliste</li>
<li>L’équation de Boltzmann : c’est une équation décrivant I’évolution de la distribution des particules
soumises aux forces dans un systéme.
Introduction générale
exemple, les interactions des particules dans la matiere sont décrites par des sections efficaces
d’interaction représentant la probabilité que la particule interagisse dans le milieu.
Dans le cadre de la physique médicale, les domaines d’application des simulations de
Monte Carlo sont nombreux : la médecine nucléaire, '’hadronthérapie,la radiothérapie, la
curiethérapie. . .
Ce mémoire a été réalisé en six chapitres.
Dans le premier chapitre nous allons voir quelques notions physiques en oncologie, y
compris la définition de la radiothérapie, la hadronthérapie et nous parlerons aussi des inter-
actions des particules (électron, photon, les ions carbones et le proton) utilisées en traitement
avec la matiére.
Au cours de deuxiéme chapitre nous traiterons quelques généralités préliminaires de la
méthode Monte Carlo, principe de la méthode, génération de nombre aléatoire, et on termi-
nera ce chapitre par deux applications de base illustrant I'utilisation de celle-ci.
Le troisiéme chapitre aborde différents codes Monte Carlo utilisés a la simulation des
particules et I'imagerie dont on distingue deux types, les codes généraux et les codes dédiés
L’objectif de quatriéme chapitre est consacré a étudier le transport et transfert d’énergie
par les électrons, les photons et des ions en parlant des algorithmes et les étapes de simulation
par méthode Monte-Carlo qui est basée sur la génération de nombres aléatoires.
Le chapitre 5 a pour but de présenter le code de simulation PHITS en détaillant sa
structure générale et fichier d’entré (input), nous allons parler aussi en fin de ce chapitre des
modéles physique qui sont introduit dans le code.
En fin, nous allons terminer notre mémoire par le chapitre 6 dont on va présenter quelques
résultats avec discussion, pour ceci nous devons d’abord valider le code utilisé on se basant
sur des mesures publices par NASA et aprés on étudiera les caractéristiques balistiques
de faisceau ionique (proton et ions de carbone) , la distribution de dose en profondeur et
latéralement .</li>
</ol>
<h1 id="chapitre-1"><a class="header" href="#chapitre-1">CHAPITRE 1</a></h1>
<h2 id="notions-physiques-en-oncologie"><a class="header" href="#notions-physiques-en-oncologie">NOTIONS PHYSIQUES EN ONCOLOGIE</a></h2>
<h3 id="11-introduction"><a class="header" href="#11-introduction">1.1 Introduction</a></h3>
<p>La thérapie de cancer par rayonnement est une méthode médicale utilisant les rayon-
nements ionisants pour détruire les cellules cancéreuses tout en protégeant les tissus sains.
Cette technique a été développée suite a la découverte des rayons X par W.K Rontgen en
1895 et vise a administrer de maniére trés précise une dose de rayonnement a la zone af-
fectée par la tumeur. Les appareils modernes sont des accélérateurs linéaires, cyclotron et
synchrotron , qui produisent des faisceaux de particules de haute énergie[5].
La thérapie par rayonnement peut étre utilisée en combinaison avec d’autres traitements,
tels que la chirurgie et la chimiothérapie, en fonction du type de tumeur, de son emplacement,
de son stade et de I'état de santé général du patient.</p>
<h2 id="12-la-radiothérapie"><a class="header" href="#12-la-radiothérapie">1.2 La radiothérapie</a></h2>
<h3 id="121-radiothérapie-externe"><a class="header" href="#121-radiothérapie-externe">1.2.1 Radiothérapie externe</a></h3>
<p>La radiothérapie externe est une méthode courante de traitement anticancéreux qui utilise
des rayonnements ionisants, les photons et les électrons, provenant d’une source externe au
patient. Cette méthode de traitement peut étre curative, palliative en fonction de la tumeur
a traiter, de sa localisation, de sa taille, de son stade et de I’état général du patient.</p>
<h3 id="122-radiothérapie-interne"><a class="header" href="#122-radiothérapie-interne">1.2.2 Radiothérapie interne</a></h3>
<p>Cette technique consiste &amp; mettre directement en contact des sources radioactives avec
la tumeur, elle permet de délivrer une dose trés élevée directement au contact de la tumeur,
tout en limitant 'irradiation des tissus sains. Les techniques de radiothérapie interne varient
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
en fonction de la nature et de la localisation de la tumeur.
1.2.3 Transfert d’énergie par les photons
En radiothérapie externe, on utilise des rayons X de trés haute énergie, entre 4 et 25
MeV.
Sous ces niveaux d’énergie 4 types d’interactions peuvent se produire entre les photons et
la matiére : I'effet Compton, l'effet Photo-électrique, la Création de paires, 'effet Thomson-
Rayleigh [5],[6],]7]
Effet photoélectrique
L’énergie du photon incident hv est totalement communiquée a un électron plus profond
de 'atome, qui est éjecté de sa couche électronique en produisant l'ionisation de l'atome.
Son énergie cinétique est :
E.=hv—E 1)
olt h = 6.62 x 10734 J - s est la constante de Planck et F; est 'énergie de liaison de I'électron
sur sa couche.
La section efficace ou probabilité pour avoir cet effet dépend fortement de 'énergie du
photon incident et du numéro atomique Z de l'atome :
Ope = Z° | B3P 2)
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
o Photoélectron
Te-=hv,-E,
Photon de fluorescence
hv=E,- E
\ 7
\ M ou
El
Photon incident
hy,
ectron Auger €
FIGURE 1.1 - Le processus ionisant : effet photoélectrique [8]
Diffusion de Compton
La diffusion Compton est une collision entre un photon hiy et un électron de valence fai-
blement lié. Le photon est alors diffusé avec une énergie hv inférieure a son énergie incidente
et I'électron, dit de recul, est éjecté avec une énergie cinétique complémentaire de 1'énergie
du photon diffusé en provoquant une ionisation ultérieure.
Eo
1+ a(1l — cosb)
E. = Ey— Egg = Ey (MeV) (3)
o&gt; = 0,511 MeV.
avec o = E“2
MeC
La distribution en angle, ou la section efficace différentielle!, des photons diffusés par
effet Compton est donnée par la formule suivante [Compton(1923)] :
doxn r2 1 L g a?(1 — cos )2
( dQ ) (o 6) = 2 (14 a(l — cosb))? Ltcostf+ 14 a(1l—cosb) @
Dans le cas de la radiothérapie, l'effet photoélectrique est prédominant pour des éner-
gies inférieures a 100 KeV dans le corps humain. C’est l'effet prépondérant en Radiologie
conventionnelle.</p>
<ol>
<li>La section efficace différentielle : représente la probabilité d’interaction deux particule en tenant compte
a la fois I'angle de déviation et I’énergie des particules incidentes.
6
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
Electron Compton
o
Photon incident Electron
l\]l]J[ ------- &gt;0 faiblement lié
g &amp;
Photon diffusé g
hv’ <br />
FIGURE 1.2 - Le processus ionisant :effet Compton [8]
Création de paire électronique
Dans un champ électrique intense existant prés du noyau, les photons incidents d’énergie
supérieure a 1,022 MeV peuvent apparaitre sous forme d’électrons et de positrons, proces-
sus appelé matérialisation. Les électrons et les positrons sont ralentis dans la matiére par
les collisions. Lorsqu’ils sont suffisamment lents, un positron peut rencontrer un électron
intermédiaire et les deux particules s’annihilent, émettant ainsi deux photons de 0,511 MeV.
Dans ce cas, la section efficace dépend de I'énergie du photon incident et du numéro
atomique Z de 'atome :
Oep =72 E (5)
Photon incident
1\71]/[ _______ &gt; ‘ Noyau
hv,
e+ ®
FIGURE 1.3 — Le processus de création de paire électronique [8]
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
Les principales interactions des photons de haute énergie utilisés sont : 1'effet Compton
entre 0,3-20 MeV et l'effet De création de paires au-dela de 1,02 MeV toute cette interaction
aboutit &amp; la création d’électrons énergétiques.
effet photoélectrique effet de
matérialisation
effet
Compton
100 EenMeV
FIGURE 1.4 — Domaine de prédominance des différentes interactions fondamentales [9]
Effet de Rayleigh
L’effet de Rayleigh se manifeste par la diffusion d’un photon sans changement d’énergie,
autrement dit, une collision élastique du photon incident avec le nuage électronique. Il est
plus fréquent aux faibles énergies, notamment pour celles inférieures a 40 keV, et son impact
sur le corps humain est relativement faible comparé a d’autres interactions possibles entre le
rayonnement et la matiére.
Photon diffusé
hv
Photon incident pe
e
FIGURE 1.5 - la diffusion Rayleigh
1.2.4 Transfert d’énergie par les électrons</li>
</ol>
<hr />
<p>Dans le processus de transfert d’énergie, les électrons en mouvement interagissent avec
les électrons des atomes du milieu. Ainsi, un électron peut interagir avec plusieurs atomes
8
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
sur son parcours, les principales interactions des électrons avec les atomes incluent :
— La diffusion élastique : simple déviation de 1’électron incident.
— La diffusion inélastique : provoque I'éjection d'un électron de I'atome.
— Le rayonnement de freinage : ’électron est freiné et dévié en passant au voisinage
d’un noyau atomique.
L’énergie perdue par ’électron est emportée par un photon, qui pourra interagir avec la
matiére plus loin. La trajectoire d’un électron est une allure chaotique? et son parcours
borné (voir figure 1.6).
La distance moyenne de parcours d’un électron est proportionnelle &amp; son énergie initiale
et inversement proportionnelle &amp; la densité électronique du matériau.
trajectoire
électron
portée
FIGURE 1.6 — La trajectoire d'un électron dans les tissus [9]
1.3 La hadronthérapie
1.3.1 Principe
La hadronthérapie est une technique anticancéreuse permet de détruire les cellules can-
céreuses radiorésistantes [10] en les irradiant avec un faisceau des hadrons (neutron, proton,
ion ...) notamment des protons (on parle dans ce cas de protonthérapie) [11], [12] et des
ions carbone (on parle dans ce cas de carbonethérapie) [13].
Les hadrons signifient en grec forces, constituent des quarks (particules élemantaires du
noyau ) ils sont utilisés pour les protons et les neutrons en thérapie tumorale et par extenson
pour les noyaux atomiques comme hélium,oxygeéne , carbon néon et 'argon [14].
2. La trajectoire d’un électron est chaotique : c’est une trajectoire de forme en zig-zag ceci est du au
nombre elevé d’interaction effectuées par un électron dans un milieu.
9
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
1.3.2 Interactions des ions avec la matiére
Le passage des ions, les protons les ions de carbone, dans la matiére fait intervenir diffé-
rentes types d’interactions [6], [15] ,[16].
Collisions élastiques
Les particules perdent leur énergies cinétique en interagissant avec le nuage électronique
des atomes, ce type de collisions sont observées pour les particules de faibles énergie ( moins
de 100 eV ) généralement leurs contribution est négligeable.
Collisions inélastiques
Les particules perdent leurs énergies cinétiques en interagissant avec le nuage électronique
des atomes de milieu qui conduisent a l'excitation voire l'ionisation selon 1'énergie, ce type
de collisions est probable pour I’énergie de particule incidente dépasse 10 KeV .
SO S S S LSS ST LS IS
N TN TN SN N
N ;IQ N e e
TN N
AN
®
ure
lonisation
Q
®
Q
50)
WET7 HLL7 IS
)
J
Qy&gt;§
®y)..
)
Q)
)
Double ionisation Double capture Transfert ionisation
O lonprojectile .Atome cible @ Electron
FIGURE 1.7 — Représentation schématique des différents processus inélastiques élémentaires
pouvant étre induits lors de collisions ions — atomes [5]
Collisions élastiques avec le noyau
La particule incidente est déviée sans émission électromagnétique ni excitation du noyau;
le phénomeéne est régi par les lois de la mécanique classique, la particule chargée ne perdant
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
que ’énergie cinétique nécessaire a la conservation des moments des deux particules, ce type
de collisions est prépondéré pour quelques KeV.
FIGURE 1.8 - La diffusion élastique avec les noyaux de la cible [7]
Collisions nucléaires inélastiques
Lorsque ’énergie de projectile est supérieure a la barriére coulombienne, le projectile peut
franchir cette barriére alors les réactions noyau-noyau deviennent dominantes , ces collision
son principalement périphériques|17]
Dans ce type de collisions le systéme est excité voire transformé (Abrasion) et conduisant
a la fragmentation des ions (ablation) 4 et de cible.
fragment projectile
projectile » * o evap.
Vf ~ Vp
N S
A. bouledefeu N pdt
\ o n
fragment cible
cible
Abrasion Ablation
FIGURE 1.9 — Un modéle simplifié¢ de la fragmentation nucléaire due aux collisions périphé-
riques du noyau du projectile et de la cible tel que décrit par Serber [18]
3. L’abrasion correspond a la collison entre deux noyaux en perdant leurs énergie , ce phénoméne est
remarquable pour les ions lourds
4. L’ablation : C’est un phénomene réalisé lors de collision des ions de haute énergie en produisant des
fragments moins légers
11
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
1.3.3 Propriétés physiques des hadrons
Les avantages de I’hadronthérapie par rapport a la radiothérapie conventionnelle par
photon sont les suivants [19] , [11] :
— Les protons et les ions se traduisant par une précision balistique dont le dépot de dose
en profondeur est localisé, le pic de Bragg, avec une faible dispersion latéralement et
en profondeur, ceci permet de détruire les cellules tumorales.
— L’effet biologique des ions de carbone est plus important que celui de proton d’ou
lavantage principal des ions de carbone par rapport aux protons [20].
— Le transfert d’énergie linéique de l'ion carbone est important que de proton et de
photon.
100] = a
~ |7 ~ Photon &quot;Ii
s ~ o
&lt; So S
g ~ s
Nt i
50 frenmrernannnnnnneete &lt;L !
Proton ;l\ i
_————— - .:. S~ -
Profondeur dans les tissus (cm)
FIGURE 1.10 - Distribution de la dose versus la profondeur pour différents types de radiations
dans un tissu
1.3.4 Transfert d’énergie linéique
Le transfert d’énergie linéique, abrégé TEL, exprimé en keV /pm, traduit I’énergie moyenne
transmise au milieu par la particule dFi,ans par unité de longueur dx comme le montre 1'équa-
tion suivante :
dEtrans dE
e = E
dx dx Z s ©
dE
Avec : = @ pouvoir d’arrét [4],[5],[21] .
TEL =
12
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE</p>
<blockquote>
<p>E5s : somme des énergies par unité de longueur des particules sortantes (électrons ) du</p>
</blockquote>
<hr />
<p>volume considéré [19].
Nous considérons un petit rayon r du cylindre, et donc le TEL ne prend pas en compte les
électrons secondaires qui vont déposer leur énergie en dehors du cylindre. En bas, le cylindre
posséde un rayon assez élevé R, et donc nous pouvons faire I’approximation que TEL = %.
e</p>
<ul>
<li>m T
. TELg= dE/dx
FIGURE 1.11 - Schémas d’illustrations pour la prise en compte du calcul du TEL
[22]
Plus ce paramétre est grand, plus les dégats biologiques aux tissus traversés sont impor-
tants.
1.3.5 Définition de la dose
Dose physique
La dose déposée ou dose absorbée par les tissus, notée D et exprimée en Gray (J/kg),
représente l'énergie moyenne déposée par les particules ionisantes de dans un volume de
masse dm, et est donnée par la relation suivante [15] :
de
= (7
D’autre part, la dose est définie comme le produit de la fluence F' et du pouvoir d’arrét
massique 2£ - %, sous la forme [15] :
13
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
Dose biologique
La dose biologique ou dose équivalente photons, notée Do et exprimée en Gray Equi-
valent Cobalt (60Co), est définie par [19] :
Dyt = D -EBR (9)
avec EBR : IEfficacité¢ Biologique Relative, sans unité. Pour les protons (protonthérapie),
on utilise EBR = 1.1 quelles que soient les conditions de calcul. Cependant, EBR est entre
2 et 3 pour les ions de carbone (carbonethérapie).
Intéraction particule - matiére biologique
L’interaction des particules ionisantes avec la matiére biologique a pour effet d’endom-
mage ’ADN directement ou indirectement par destruction de la molécule de I'eau en deux
radicaux libres actifs chimiquement qui attaque la matiére par des réactions chimiques, la
figure 1.12 présente une architecture de cette interaction.
Effet
lonisation de 'ADN
Effet
direct
Man, indirect
w Ionisation d’autres
Cellule molécules (ex: H,0)
Cellule
Oxydation de 'ADN £ <br />
par les radicaux libres endommagée w
DOIIIEES Mort Réparation
permanents
— A
. (@) .
FIGURE 1.12 — Séquence schématisée des effets biologiques
[23]
14
CHAPITRE 1. NOTIONS PHYSIQUES EN ONCOLOGIE
1.4 Conclusion
Le traitement des tumeurs cancéreuses utilise des particules ionisantes, qui transportent
de D'énergie aux tumeurs en déclenchant les processus d’ionisation des tissus cibles. La
connaissance de ces processus de transport des particules utilisées est indispensable pour
optimiser le traitement et minimiser le risque sur les tissus sains environnants.
15
CHAPITRE 2
GENERALITES SUR LA METHODE DE MONTE CARLO
2.1 Introduction
Les calculs de Monte Carlo font appel a une méthode statistique basée sur 1'utilisation
des nombres aléatoires comparables &amp; ceux produits par les jeux de hasard dans les casinos.
Dans ce contexte, on distingue deux grands domaines ot la méthode de Monte Carlo peut
étre utilisée avec succes [9).
Problémes déterministes
Ce sont des problémes de nature déterministe faisant appel aux calculs numériques, par
exemple :
— Estimation des surfaces .
— Calculs d’intégrales multiples.
— Résolution d’équation différentielle.
— Résolution de systemes d’équations algébriques.
— Résolution de problémes d’optimisation combinatoire
Phénomeénes et processus aléatoire
— Mouvement de particules.
— Systémes stochastiques de gestion ou de production.
— Reconnaissance de formes (analyse d’images, de paroles, .. .).
— Systémes de commande décrits par des équations différentielles ordinaires ou des
équations aux différences.
16
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
2.2 Générateur de nombres aléatoires
2.2.1 Principe
La simulation Monte Carlo repose toujours sur un générateur de nombres aléatoires
fiable. On appelle nombres aléatoires des variables aléatoires indépendantes uniformément
distribuées sur Uintervalle [0,1].
Générateur de
nombres aléatoires
Modeéle de diffusion
(Algorithmes, sections efficaces d’interactions, ...)
FIGURE 2.1 — Représentation schématique de principe de méthodes Monte Carlo [24]
2.2.2  Nombres véritablement aléatoires
Les nombres vraiment aléatoires sont imprévisibles, ils ne sont pas générés par un proces-
sus déterministe et doivent étre produits par un processus physique aléatoire , par exemple la
désintégration radioactive , 'impact de la séparation des rayons cosmiques sur les détecteurs
ou la synchronisation de la génération de bruit dans les circuits électroniques. [4], [16].
2.2.3 Nombres pseudo-aléatoires
A Taide d’un ordinateur nous pouvons utiliser des nombres dits pseudo-aléatoires [25],
qui sont générés par un algorithme congu pour produire une séquence de nombres non cor-
rélés et uniformément répartis dans un intervalle donné. Les chiffres semblent complétement
aléatoires d'un point de vue extérieur, mais ils montrent un schéma récurant.
En pratique, nous n’utilisons pas de vrais nombres aléatoires, désormais nous appellerons
les nombres pseudo-aléatoires nombres aléatoires.
17
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
En général, un générateur de nombres aléatoires doit répondre aux conditions de base sui-
vantes :
— La distribution des nombres aléatoires doit étre uniformément répartie dans un inter-
valle spécifique, et doit répondre a des tests de cohérence et d’indépendance.
— La séquence comporte un grand nombre des nombres uniques avant de répéter la
boucle.
— La génération de nombres aléatoires est trés rapide [16].
2.3 Les méthodes principales d’échantillonnage
2.3.1 Principe
La méthode de Monte Carlo (MC) consiste a échantillonner la distribution de probabilités
décrivant un processus physique en utilisant des nombres aléatoires. Il existe trois méthodes
principales d’échantillonnage :la méthode d’inversion directe, la méthode de réjection et la
méthode de composition [16],[12] ,[13].
2.3.2 La méthode d’inversion directe
Nous utilisons la méthode d’inversion directe lorsque la fonction de répartition de la</li>
</ul>
<hr />
<p>variable aléatoire, qui renvoie la probabilité de prendre une valeur inférieure ou égale a x,
peut étre inversée. Puisque y = F(x) est uniformément distribué¢ entre 0 (la probabilité que
la variable aléatoire ne prenne aucune valeur) et 1 (la probabilité que la variable aléatoire
prenne n’importe quelle valeur), la variable x = F~!(y) obé¢it a la fonction de distribution
p(x) = Fy(x). 11 suffit donc de générer une suite de valeurs R uniformément réparties entre
0 et 1, puis d’utiliser x = F'~1(R) pour obtenir les valeurs selon p(x).
Par exemple, la profondeur d’interaction = des rayons gamma pénétrant dans un matériau
d’épaisseur d et de coefficient d’atténuation p est une variable aléatoire caractérisée par la
fonction de partition :
18
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
La relation entre F(x) et p(x) est donnée par :
F(x) =1— exp(—px) (10)
Ou i est un parameétre. La fonction de distribution est alors :
p(x) = pexp(—px) (11)
Si R est uniformément distribué¢ dans Uintervalle [0, 1], alors la variable
1
z=—=In(1 - R) (12)
1
sera automatiquement distribuée selon p(x).
La probabilité que la variable x soit supérieure a d est la probabilité que le rayon gamma
n’interagisse pas dans le matériau. Elle est égale a :
exp(—pd) =1— F(d) (13)
11 détermine ainsi la proportion d’impressions qui n’entrainent pas d’interactions d’épaisseur
de matériau et caractérise en quelque sorte 'inefficacité du processus de simulation pour
cette tache [15].
19
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
2.3.3 La méthode de réjection
Une autre méthode d’échantillonnage a été proposée par Von Neumann. Elle consiste a
tirer uniformément une variable aléatoire R dans l'intervalle [0, 1] d’une distribution (autre
que p(z)) et &amp; la tester au hasard pour déterminer si elle est acceptée ou rejetée. Ces méthodes
de rejet conduisent a une technique trés générale d’échantillonnage a partir de n’importe
quelle fonction de densité de probabilité (PDF) et a déterminer sa valeur correspondante en
utilisant la régle d’échelle affine :
T = Tyin + R(]:max - xmin) (14&gt;
dans le domaine variable D = [%pin, Tmax] d’une variable aléatoire. La valeur de z pour
le deuxiéme graphe est affectée en fonction de p(z),tandis que le deuxiéme graphe R’ est
uniformément réparti entre 0 et 1.
Cela permet de conserver z si Ry est inférieur ou égal a f(z) = ﬁ;gz)}, si non on le rejette
[2]-
f(x)
Xinin Xmax
FIGURE 2.2 — :Méthode de réjection : Fonction de probabilité normalisée f(x) méthode de
rejet [14]
20
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
2.3.4 La méthode de composition
Si les deux méthodes précédentes ne sont pas applicables, une méthode combinant les
deux peut étre utilisée.
Soit deux fonctions de densités de probabilités normalisées a 1 : f4(x) et f(x) définies par
la relation suivante :
@) = fi(@) - fp(o) (15)
On utilise alors la méthode directe pour sélectionner x en utilisant f}(x) comme fonction
de densité de probabilité normalisée. Ensuite, on applique la méthode de rejet sur la fonction
f5(2).
2.4 Précision d’un code Monte Carlo
2.4.1 Incertitudes physiques
Quelle que soit la précision des données physiques utilisées dans un code de Monte Carlo,
la qualité des résultats est inévitablement limitée par le modeéle de diffusion utilisé ,la maniére
dont les sections efficaces sont tabulées interpolées et échantillonnées peut introduire des
erreurs supplémentaires.
2.4.2 Incertitudes statistiques
Les résultats des calculs de Monte Carlo sont également soumis a une incertitude statis-
tique. Pour éviter les fluctuations statistiques, un certain nombre de particules (des centaines
a des milliards de particules) doivent étre simulées [24].
En effet, plus le nombre d’histoires N généré est important, plus 'incertitude associée a la
grandeur calculée dans le volume d’intérét sera petite plus le résultat estimé par MC est
proche de la réalité. L'incertitude statistique associée o, correspondant &amp; I’écart-type sur la
21
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
moyenne G, est déterminée a partir de la relation suivante :
ou :
— 0 : est l'incertitude statistique associ¢e a la moyenne G.
— N : est la taille de I’échantillon, c¢’est-a-dire le nombre de valeurs dans 1’échantillon
— ¢; : représente les valeurs individuelles dans 1’échantillon.
— G : est la moyenne des valeurs dans I’échantillon.
Ce type d’incertitude est li¢ aux modéles physiques utilisés pour déterminer la section efficace
et le pouvoir d’arrét. Ainsi, il est affecté par les erreurs de programmation.
2.5 Efficacité d’une simulation Monte Carlo
L’efficacité ¢ d'une simulation permet de comparer les performances de deux méthodes
de simulation. L’efficacité est définie par la relation :
AN 2
1 /G
e=—[— 17
(9 (7)
Ot T représente le temps de calcul, o2 est la variance de I'estimation et G est la moyenne.
L’efficacité d’un code de Monte Carlo dépend en grande partie de la qualité de son générateur
de nombres aléatoires.
2.6 Estimation de la valeur m par Monte Carlo
La méthode de Monte Carlo permet la résolution de certains problémes numériques dé-
terministes.Elle résout les problémes de fagon approchée avec une simulation [16].
Dans ce paragraphe, nous présentons briévement 1’approximation du nombre 7 par I'estima-
22
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
tion de la surface d’'un quart de disque de forme circulaire de rayon 1.
2.6.1 Algorithme
Dans ce cas, on tire au hasard des coordonnées x et y, chacune dans Uintervalle [0, 1[.
Si 2% + y? &lt; 1, alors le point P de coordonnées (,y) appartient au quart de disque D de
centre (0,0) et de rayon 1. La probabilité que count_inside appartienne &amp; D est 7/4 (rapport
de laire de D et du carré I'englobant). Donc, si on tire au hasard num_ points points, et si</p>
<hr />
<p>count_inside d’entre eux appartiennent &amp; D, on obtient une approximation de 7 égale a : [26]
count__inside
™= -
num__points
2.6.2 Code de simulation
import random
import matplotlib.pyplot as plt</p>
<h1 id="nombre-de-points--utiliser-pour-1lestimation"><a class="header" href="#nombre-de-points--utiliser-pour-1lestimation">Nombre de points &amp; utiliser pour 1l’estimation</a></h1>
<p>num_points = 10000</p>
<h1 id="compteur-pour-les-points-dans-le-cercle"><a class="header" href="#compteur-pour-les-points-dans-le-cercle">Compteur pour les points dans le cercle</a></h1>
<p>count_inside = 0</p>
<h1 id="listes-pour-stocker-les-coordonnées-des-points-dans-et-hors-du-cercle"><a class="header" href="#listes-pour-stocker-les-coordonnées-des-points-dans-et-hors-du-cercle">Listes pour stocker les coordonnées des points dans et hors du cercle</a></h1>
<p>x_inside = []
y_inside = []
x_outside = []
y_outside = []
23
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO</p>
<pre><code class="language-py"># Boucle pour générer des points aléatoires
for i in range(num_points):
# Générer des coordonnées x et y aléatoires
x = random.uniform(-1, 1)
y = random.uniform(-1, 1)
# Calculer la distance par rapport &amp; l’origine (0,0)
distance = (x ** 2 + y **x 2) **x 0.5
# Si la distance est inférieure ou égale &amp; 1,le point est al’intérieur du cercle
if distance &lt;= 1:
count_inside += 1
x_inside.append(x)
y_inside.append(y)
else:
x_outside.append(x)
y_outside.append(y)
# Calculer Pi en utilisant le nombre de points &amp; 1’intérieur et &amp; 1l’extérieur du cercle
pi = 4 * count_inside / num_points
# Afficher le résultat
print(&quot;Pi est estimé &amp; :&quot;, pi)
# Créer un graphique pour visualiser les points dans et hors du cercle
fig, ax = plt.subplots()
ax.set_aspect(’equal’, ’box’)
</code></pre>
<h1 id="tracez-les-points-dans-et-hors-du-cercle"><a class="header" href="#tracez-les-points-dans-et-hors-du-cercle">Tracez les points dans et hors du cercle</a></h1>
<p>ax.scatter(x_inside, y_inside, color=’blue’, marker=’.’)
ax.scatter(x_outside, y_outside, color=’red’, marker=’.’)</p>
<h1 id="ajouter-un-cercle-inscrit-dans-le-carré-pour-représenter-le-cercle-unité"><a class="header" href="#ajouter-un-cercle-inscrit-dans-le-carré-pour-représenter-le-cercle-unité">Ajouter un cercle inscrit dans le carré pour représenter le cercle unité</a></h1>
<p>circle = plt.Circle((0, 0), 1, color=’green’, fill=False)
ax.add_artist(circle)</p>
<h1 id="ajouter-une-légende-pour-les-points"><a class="header" href="#ajouter-une-légende-pour-les-points">Ajouter une légende pour les points</a></h1>
<p>ax.legend([’Points dans le cercle’,’Points hors du cercle’])</p>
<h1 id="afficher-le-graphique"><a class="header" href="#afficher-le-graphique">Afficher le graphique</a></h1>
<p>plt.show()</p>
<pre><code>
2.6.3 Résultats et discussion
Pi est estimé a : 3.136
Pi est estimé a : 3.1424
1.00
1001 « Points dans le cercle
075 « Points hors du cercle &amp;%
’ 0.75 4 ) 5 §
0.50
0.50 4
0.25 0254
0.00 0.004
—0.25 -0.259
~0:504 -0.50 4
-0.754 &gt;
Points dans le cercle ? x —0.759
- 4 Points hors du cercle = A
1.00 - * - * -1.00 {
.
-1.0 -0.5 00 0.5 10 -1.0 -0.5 0.0 05 1.0
(a) (b)
FIGURE 2.3 — La visualisation des points dans et hors de cercle :(a) pour N=1000 points, (b)
pour N=10000 points
25
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
Estimation de Pi par la méthode Monte Carlo
4.0 —— Estimation de Pi
-—- Piréel
35
3.0
25
Valeur de Pi
20
15
0 2000 4000 6000 8000 10000
Nombre de points
FIGURE 2.4 — Les valeurs de pi estimées en fonction de nombres de points
N,=100 N,=1000 N;=10000 | N,=100000 | N;=1000000 | No=10000000|  N,=10°
Valeur : 1 3,20 3,076 3,1372 3,14652 3,1424760 _ [3,1412456 _ |3,14156936
valeur : 2 3,00 3,144 3,1368 3,15096 3,1406160  [3,1431852  |3,1416459
valeur : 3 3,08 3,136 3,1384 3,13928 3,1426600  [3,1413736 _ |3,14145948
valeur : 4 3,00 3,064 3,1340 3,13956 3,1429120  [3,1415700 _ |3,14160688
valeur : 5 3,32 3,168 3,1528 3,14884 3,1428520  [3,1416780 _ |3,14197648
valeur : 6 2,9 3,128 3,1356 3,15056 3,1432280  [3,1418452 _ [3,14154292
valeur : 7 3,20 3,176 3,1152 3,13412 3,1446400  [3,1418824 _ |3,14100000
valeur : 8 3,16 3,080 3,1344 3,13712 3,1421600 _ [3,1409984 _ |3,14100000
valeur : 9 3,32 3,112 3,1756 3,14672 3,1418160 _ [3,1413516 _ |3,14100000
valeur : 10 2,92 3,216 3,1244 3,14768 3,1407720 _ [3,1413212 _ |3,14100000
moyenne 3,116 3,1300 3,13844 3,144136 3,1424132 _ [3,14164512 |3,141380108
erreure relative %|0,814639465 |0,369005624 |0,100352081 |0,080957231 |0,026118803 |0,001670058 |0,006765536
ECARTYPE 0,145388369 |0,048634693 |0,016236529 |0,00604564 _|0,001177236_|0,00060714 _ |0,000353446
FIGURE 2.5 - La valeur moyenne estimée de 7 par Monte Carlo pour un nombre de points
donné avec 'erreur relative et I'écart-type
A partir des résultats obtenus par la simulation, nous concluons :
— Lorsque N augmente, les valeurs de 7 estimées se rapprochent de plus en plus de la
valeur exacte, mais le temps de calcul augmente également (voir Figure 2.4).
— Chaque fois que nous effectuons un nouveau tirage pour la méme valeur de N, nous
obtenons une autre valeur différente estimée de 7, en raison de la nature basée sur les
variables aléatoires (voir Tableau 2.5).
— Le caractére aléatoire de la méthode Monte Carlo nous pousse a répéter les tirages
plusieurs fois afin d’estimer la valeur moyenne de 7.
26
CHAPITRE 2. GENERALITES SUR LA METHODE DE MONTE CARLO
2.7 Conclusion
En conclusion, pour obtenir des résultats précis avec une incertitude acceptable, il est
indispensable de simuler le transport d'un grand nombre de particules (au moins de 'ordre
de 107). Cela implique des temps de calcul relativement longs, pouvant atteindre plusieurs
jours [9].
27
CHAPITRE 3
CODES DE SIMULATIONS PAR MONTE CARLO
3.1 introduction
De nombreux logiciels de simulation Monte Carlo ont été développés pour des applications
dans des domaines tels que la physique médicale, la médecine nucléaire ou la dosimétrie
interne. Certains de ces codes de calcul sont dans le domaine public et sont disponibles
gratuitement. Les techniques de Monte Carlo sont avérées idéales pour le transport des
particules et sont considérées comme les plus efficaces pour estimer la distribution spatiale
des particules et le dépot d’énergie. Les codes Monte Carlo utilisés en médecine peuvent se
classer en deux catégories :les codes généraux et les codes dédiés.
Dans ce chapitre nous allons donner une idée générale sur des codes utilisés principalement
dans le domaine de médecine et le domaine de recherche dont on distingue entre deux type
de code.
3.2 Codes généraux
3.2.1 Penelope
Penelope simule le transport couplé électron-photon dans des systémes matériels arbi-
traires constitués d’un certain nombre de régions homogenes (corps) limitées par des in-
terfaces nettes (et passives). Initialement, il a été congu pour simuler la pénétration et les


------

pertes d’énergie des positrons et des électrons dans la matiére; les photons ont été intro-
duits plus tard. Les modeles d’interaction adoptés (diffusion Rayleigh, diffusion Compton,
effet photoélectrique et production de paires et I’annihilation des positons sont simulés de
maniére détaillée), et les bases de données associées, permettent de simuler le transport des
électrons /positrons et des photons dans la gamme d’énergie allant de 50 eV a 1 GeV.
28
CHAPITRE 3. CODES DE SIMULATIONS PAR MONTE CARLO
3.2.2 EGS (Electron Gamma Shower)
EGS (Electron Gamma Shower) est un code de calcul Monte Carlo développé dés 1963 au
SLAC par Nagel (Nagel 1964) pour simuler des gerbes électromagnétiques de haute énergie
(de quelques KeV a plusieurs TeV) dans des géométries arbitraires .C’est un code dit de classe
11, pour lequel les productions d’électrons de collisions et d’électrons &quot;bremsstrahlung&quot; sont
traités individuellement. Une nouvelle version EGS4 (Nelson, Hirayama et al. 1985), inclut
un transport d’électrons de basse énergie (jusqu’a 1 KeV) amélioré, ainsi que la simulation
de la diffusion Rayleigh. Une version plus récente de EGS4 a été développée sous le nom de
(de quelques keV a plusieursTeV) dans des géométries arbitraires. C'est un code dit de classe
11, pour lequel les productions d’électrons de collision et d’électrons &quot;bremsstrahlung&quot; sont
traités individuellement. Une nouvelle version, EGS4 (Nelson, Hirayama et al. 1985), inclut
un transport d’électrons de basse énergie (jusqu’al keV) amélioré, ainsi que la simulation
de la diffusion Rayleigh. Une version plus récente de EGS4 a été développée sous le nom
de GSnre (Kawrakow and Rogers2002), comparé au code précédent EGS4, le code EGSnec
propose une simulation plus précise des interactions des électrons et du positon. Il incorpore
aussi une extension des tableaux de sections efficaces relatives aux photons de basse énergie.
3.2.3 Le code MCNP
MCNP (Monte-Carlo Neutron Photon) est un logiciel développé par Breismeister [27]. 11
suit les particules neutres (photons et neutrons), les électrons(positifs et négatifs) et dont la
derniére version MCNPX, est étendue a certaines particules lourdes chargées.
Ce code est directement li¢ a I'origine au projet Manhattan. Initialement, ce code ne pre-
nait en compte que le transport des particules non chargées comme les neutrons et les pho-
tons. Au-dela de la modélisation de I'interaction du rayonnement avec la matiére, MCNPX
dispose d’outils statistiques pour tester la convergence mathématique du résultat obtenu
ainsi que des techniques de réduction de variance intégrées [28].
29
CHAPITRE 3. CODES DE SIMULATIONS PAR MONTE CARLO
3.2.4 Le code PHITS
PHITS (ou particle heavy and ion transport) simule la réaction et le transport de plu-
sieurs particules (une vingtaine de particules en plus d’ions lourds). PHITS est aussi utilisé
pour diverses applications comme la conception des installations d’accélérateurs et la radio-
thérapie,la hadronthérapie [29] .Nous allons voir les détails de ce code dans la suite de notre
travail .
3.25 GEANT4
GEANT4 (GEometry ANd Tracking) [30] , comme évoqué précédemment est une plate-
forme Monte Carlo pour &quot;la simulation du passage de particules &amp; travers la maticre&quot;. Ce
code est développé par la communauté de physique des hautes énergies au CERN depuis
plus de 20 ans et existe actuellement en deux versions : GEANT3 et GEANT4. GEANT3,
codé en Fortran 77, a été utilisé pendant de trés nombreuses années par la communauté des
physiciens des hautes énergies a travers le monde, et n'a cessé d’étre amélioré et débogué
grace a l'interaction des utilisateurs avec les équipes de développement. GEANT3 est actuel-
lement considéré comme un standard en physique des hautes énergies et a déja été utilisé en
physique.
3.3 Codes dédiés
Il s’agit de code monte Carlo dont les caractéristiques de conception sont optimisées
en fonction d’un domaine ou probléme spécifique. Ils sont en général trés performant mais
rarement transposables &amp; des géométries différentes .Parmi les codes dédiées a la médecine
nucléaire, on peut citer :
30
CHAPITRE 3. CODES DE SIMULATIONS PAR MONTE CARLO
3.3.1 SIMIND
Développé par le professeur Michael Ljungberg a I'université de Lund au Suede [31]. 11
est écrit en FORTRTRAN-90 .II décrit une caméra a scintillation standard adaptable pour
réaliser plusieurs applications rencontrées dans I'imagerie SPECT.
3.3.2 SimSPECT
Est un code basée sur le code MCNP [32] essentiellement pour le transport de photons
.Le code a été adapté pour faciliter la manipulation des parameétres géométriques et physique
rencontrés en imagerie SPECT .II permet aussi une simulation tomographique compléte des
sources 3D non uniformes et asymétrique .La transport de positrons est ajouté pour analyser
les différents types de collimateurs utilisés en imagerie SPECT pour des photons 511MeV ;.
3.3.3 PETsim
Est un code dédi¢ a la tomographie par émission de positron [33]
3.4 Conclusion
Les codes spécifiques sont généralement dédiés a l'imagerie scintigraphique Il n’y a pas
de code dédié au calcul de dosimétrique .Celui-ci est généralement effectué a partir des codes
généralistes.
31
CHAPITRE 4
SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE CARLO
4.1 Introduction
Le transport des particules dans la matiére étant par nature stochastique, il est tout a
fait recommandé d’utiliser les méthodes Monte Carlo pour suivre I'histoire des particules
primaires et secondaires créées au cours de la cascade d’interaction.
4.2 Simulation de transport d’une particule dans la matiére
La simulation du transport d’une particule dans la matiére par Monte Carlo se déroule
en plusieurs étapes jusqu’a ce que la particule soit absorbée, arréter par le milieu ou a quitté
les limites de volume de simulation [34].
4.2.1 Définition de la géométrie
Cette étape consiste a définir les dimensions et la forme de milieux d’interactions ou se


------

déroule la simulation. On distingue trois parameétres qui définissent ces matériaux :
— Les caractéristiques chimiques de ce milieu (la formule chimique, ...).
— Les dimensions du milieu :
— Zmin €t Tmax : sont les valeurs minimale et maximale de x, définissant la région de
positions possibles de photons dans la géométrie selon 'axe OX.
— Ymin €t Ymax : sont la valeur minimale et maximale de y, définissant la région de
positions possibles de photons dans la géométrie selon I'axe OY'.
— Zmin €t Zmax : sont les valeurs minimale et maximale de z, définissant la région de
positions possibles de photons dans la géométrie selon 'axe OZ.
Ces trois limites définissent le volume de simulation selon la forme géométrique désirée.
32
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
4.2.2 Génération des particules
Toutes les informations associées a la particule sont définies dans le code S(x; Q; F),elles
comprennent :
— La source S : génére les particules, elle peut-étre située a l'intérieur ou a l'extérieur
du domaine ou le dépot de dose a lieu.
— La position x : la position initiale ou position de départ des particules.
— L’énergie E : I'énergie d’une particule de faisceau émis par la source.
— Le cosinus directeur de la particule €2 : c’est la direction initiale des photons par
rapport a 'axe de faisceau.
4.2.3 Tirage aléatoire de la position p avant la prochaine interaction
La relation décrivant la loi de Beer-Lambert permet de donner la distance x parcourue
par la particule avant la prochaine interaction sous forme
T = %ln(f) (19)
Avec :
— ¢ : le nombre tiré aléatoirement entre 0 et 1, la variable aléatoire obéissant &amp; une loi
uniforme.
1
— = le coefficient d’atténuation total en em™
— A= 7i : le libre parcours moyen en cm.
4.2.4 Vérification de la position prochaine
Le processus de Markov qui indique que le parcours macroscopique d'une particule se
définit comme un ensemble de sous-parcours microscopiques indépendants les uns des autres,
33
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
la particule peut étre avancée a la position prochaine d’interaction
Xiy1 =X; + S Q (20)
Avec :
— X; : la position de la particule ou la effectuée une interaction i.
— X;41 : la position de la prochaine interaction ¢ + 1.
— s = Aln(¢) : la distance parcourue par une particule entre deux interactions succes-
sives.
— 2 :le vecteur directeur.
Son énergie est modifiée selon ’échantillonnage de I'interaction.
Le suivi de cette particule est stoppé quand sa position prochaine x;,1 soit en dehors de
la géométrie définie par I'utilisateur.
4.3 Transport de photons
Le type d’interaction est basée sur les sections efficaces tabulées qui dépendent du ma-
tériau, en radiothérapie, pour les énergies utilisées le photon présente quatre modes d’in-
teraction principaux :leffet photoélectrique, la diffusion Rayleigh (cohérente), la diffusion
Compton (incohérente) et la création de paires, de sections efficaces respectives notées : o,,.,
ORay, Oc €t Ocp.
Un nombre £ sera tiré aléatoirement entre 0 et 1 et quatre scénarios s’offrent a la particule
suivant sa valeur :
— Si € est inférieur a
i, on sélectionne 'effet photoélectrique.
Op.e Op.e+0Ray
Lot ——
— Si &amp; est compris entre , on sélectionne la diffusion Rayleigh.
Ip.etORay ot Op.etORaytTe
— Si¢ est compris entre , on sélectionne la diffusion de Compton.
Op.c+0Ray+0c
— Si € est supérieur a , on sélectionne la création de paires électron-positron.
34
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
4.4 Transport d’électrons et de positrons
Les électrons et les positrons sont transportés de maniére analogue dans la matiére avec
des sections efficaces identique, et sont donc traités de la méme fagon dans les codes Monte
Carlo, sauf on ajout pour le suivi de positron deux photons secondaires de 0,511 MeV émis
dos a dos (180°).
Un électron effectue un grand nombre d’interactions [35] avec une faible perte d’energie 30
eV en moyen le long de son parcours faible influence sur sa trajectoire ce qui rend le suivi
d’un électron est complexe, donc on fait appel &amp; une technique ou méthode pour résoudre ce
probléme il s’agit de technique d’histoire condensé [36].
4.4.1 La technique d’histoire condensée
Cette technique [Berger (1963)] est basée sur le fait que la plupart des interactions des
électrons avec la matiére conduit aux faibles changements d’énergie et de direction. Ces chan-
gements élémentaires sont alors regroupés en étapes et les effets globaux (énergie, direction,
déplacement latéral) échantillonnés a partir de distributions appropriées|37]
4.4.2  Algorithme de transport des électrons
La fagon la plus simple de transporter les électrons pendant un pas (Step) de I'histoire
condensée est d’ignorer la déviation due aux diffusions multiples le long de ce pas. L’électron
peut alors étre transporté le long d’une ligne. Pour accepter cette approximation, la taille
du pas doit étre suffisamment petite. Cependant, de trés petites tailles de pas conduisent a
des temps de simulation inacceptables.
4.5 Transport des protons et des ions de carbone
Le transport de protons par Monte Carlo est modélisé en divisant le trajet d'un proton en
une série de petites étapes, il est régi par trois processus principaux pouvoir d’arrét, diffusion
35
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
coulombienne et interactions nucléaires.
4.5.1 Pouvoir d’arrét
Les ions se transportent en perdant leur énergie par interaction avec des électrons ato-
miques. En Monte-Carlo, en négligeant 'interaction EM élastique et les interactions nu-
cléaires avec le noyau atomique, la perte d’énergie pour chaque étape est calculée par les
valeurs de pouvoir d’arrét sous forme de tableaux (équation de Bethe Bloch) [6],[19].
dE 4Am (nz?) e \* 2m.c?3?
= . . 1 o 32 21
dv ~ me2 B2 (471'60) {11(1-(17520 ‘/J (1)
Avec :
—p=&quot;


------

Avec :
—p=&quot;
— v : vitesse de la particule
— ¢ : vitesse de la lumiére
— E : Energie de la particule
— dx : longueur du chemin
— 2z : charge de la particule
— e : charge élémentaire
— m, : masse au repos de I'électron
— n : densité numeérique des électrons du matériau.
— [ : potentiel d’excitation moyen du matériau
FIGURE 4.1 — Echantillonnage de trajet d'un ion
36
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
Par conséquent,la perte d’énergie se dépose localement le long du trajet, sauf si le transfert
d’énergie a un électron est supérieur a une valeur seuil.
4.5.2 diffusion
La dispersion des protons accompagne le ralentissement d’ou la diminution de leur éner-
gie cinétique qui est due principalement aux interactions avec les noyaux, sachant que la
déviation de diffusion simples est assez faible pour appliquer des fonctions de densité de pro-
babilité (les théories de diffusion multiple) permettant d’accéder aux plusieurs événements
de diffusion simple, en nous pouvons appliquer la technique d’échantillonnage pour calculer
I’angle de diffusion en fin de chaque étape.
FIGURE 4.2 - Diffusion d’un ion
4.5.3 Interactions nucléaires
Les particules d'un faisceau ioniques entrent en interaction nucléaires élastiques ou inélas-
tiques avant de s’arréter elles s’accompagnent par une perte de fluence d’ott la génération de
neutrons, d’autres particules et d’isotopes a vie courte Peuvent étre prduits. La probabilité
pour avoir ces interactions est déterminée par des données de coupe efficace mesurées ou des
modéles nucléaires.
4.6 Conclusion
A travers ce chapitre nous avons vu les étapes de transport des particules dans un milieu
biologique tel que le transport des photons et les électrons qui sont des particules secondaires
37
CHAPITRE 4. SIMULATION DE TRANSPORT DES PARTICULES PAR MONTE
CARLO
dans notre étude, aprés on a parlé de celui des ions utilisé en hadronthérapie notamment
les protons et les ions de carbone 12 .Dans la suite de ce travail nous allons utiliser un code
Monte Carlo pour cet objectif.
38
CHAPITRE 5
SIMULATION PAR LE CODE PHITS
5.1 Introduction
PHITS [38] ou systéme de code de transport des particules et d’ions lourds, est I'un des
codes de simulation de transport de particules les plus réussis de Monte Carlo largement
utilisé dans le monde entier. Il peut traiter le transport de presque toutes les particules,
y compris les neutrons, les protons, les ions lourds, les photons et les électrons. .., sur une
large gamme d’énergie en utilisant divers modéles de réactions nucléaires et bibliothéques
de données. Le code PHITS est dirigé par I’Agence japonaise de 1'énergie atomique (JAEA)
[39].
PHITS est écrit en langage Fortran, est un code de type package tout-en-un, c’est-a-dire tous
les composants du code tels que ses fichiers source, exécutable et de bibliothéque de données
sont inclus dans un seul package, peut étre exécuté sur les plates-formes Windows, Mac et
Linux [39].
Dans ce chapitre nous allons décrire le code PHITS y compris 'architecture de fichier
d’entré ,les modéles physique qui sont utilsés pour dtéterminer la section efficace et le trans-
fert d’énergie linéique.
5.2 Description de fichier d’entré «input»
Le fichier d’entrée est un texte au format libre. L’utilisateur n’a pas besoin d’écrire un
programme en Fortran ni de compiler PHITS, en rendant le démarrage facile [40]. Ce fichier
a pour objectif de définir les paramétres, les variables et les formules nécessaire pour la
simulation.
- Les caractéristiques de la particule a simuler type, énergie, position et direction. . ..
39
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
- La géométrie d’espace virtuel, et les caractéristiques de matériaux.
5.2.1 Stucture de fichier input
[Title]
[Parameters]
Para1
Para 2
Para 3
[Source]
[Material]
Matfi] = Element Ratio
[Surface]
Surface number  Transform number Surface symbol Surface
[Cell]
Cell number material number  material density  cell definition  cell
FIGURE 5.1 — Architecture de fichier texte d’entré de PHITS
40
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
5.2.2  Sections de fichier input
[Title/
Comporte le titre de la simulation
[Parameters/
Dans cette section, on définit les paramétres de simulation tels que :
— Le mode de calcul et la géométrie (icntl) :
— Icnt = 1: Section efficace de sortie et facteur de kerma
— Icnt = 3 : Sortie uniquement de I’écho d’entrée pour vérifier I'utilisation de la
mémoire, les bibliothéques et les liens de fichiers
— Icntl = 0: le calcul normal de PHITS.
— Le nombre de particules a simuler (maxcas).
— Le nombre de faisceaux (maxbatch). Si maxcas = 100 et maxbatch = 2, alors 200
particules &amp; simuler.
— Les énergies de coupure (maximales et minimales)...
[Source]
Cette section donne les informations sur la production des particules par la source :
— Le type de source est défini par s-type = N, o N est un nombre spécifiant la géo-
métrie de faisceau [41].
— N =1: il s’agit d’un faisceau cylindrique.
— N =3 :il s’agit d'un faisceau Gaussien.
— N =91l s’agit d'un faisceau sphérique.
— N =18 :il s’agit d’un faisceau conique, ...
L’énergie d'une particule est e, si le faisceau est mono énergétique et e-type pour un
faisceau poly énergétique.
41
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
— La commande proj = le nom de particule émis par la source définit la nature de la
particule (électron, proton, photon, *2C, ...).
— La largeur de faisceau est indiquée par 7y (1o = 1 implique la largeur = 2 cm).
— La direction de particule est déterminée par dir avec dir = 1 selon un axe, dir = 2
dans le plan et dir = 3 dans l'espace.
La géométrie
La géomeétrie est définie par trois sections :
[Material]
Dans cette section, on définit le nombre de matériaux, le nombre d’éléments chimiques
et leur pourcentage ou abondance [41]. Par exemple :
— MAT [1] H 2 0 1 # H20
— MAT [2] 12C
[Surface]


------

— MAT [2] 12C
[Surface]
Cette section définit le nombre et la description des surfaces limitant une géométrie, telle
que la sphére (notée SO), le cylindre, le cube, ete. Par exemple :
— 1 PX 2 # plan perpendiculaire a 'axe OX en z = 2
— 2 80 5 # sphére centrée de rayon 5cm
42
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
Surface Symbol Type Explanation Equation Parameters
P plane multi-purpose Ax+By+C--D=0 A, B, C, D
PX vertical with X-axis x-D=0 D
PY vertical with Y-axis y-D=0 D
PZ vertical with Z-axis z-D=0 D
P plane defined by X1,)1,21, X2,
3 coordinates X3,¥3,73
SO sphere origin is center XY+y+2-R=0 R
S multi-purpose (x=xo) + (V=10 + (= Xo, Yo, %o, R
SX center on X-axis (x=—x0) +1° += X0, R
SY center on Y-axis X+ -y)+ o, R
SZ center on Z-axis X+ (- 0. R
C/X cylinder parallel with X-axis V=) +(—z) -R = Y0, 0, R
C/Y parallel with Y-axis (x=x0) + (=) -R? Xo. Zo» R
C/Z parallel with Z-axis (x— xo)' + (y —y) - R- =0 xo, Yo. R
[©:¢ on X-axis Y+ -R=0 R
cY on Y-axis ¥+2-R=0 R
Ccz on Z-axis X+ -R*=0 R
K/X cone parallel with X-axis VO =90+ -2 Fltl(x—x) =0 Xo» Yo» 0. It k
K/Y parallel with Y-axis Vx—x02 + (=20 Fll(y=10) =0 Xo, Yo, o, |t k
K/Z parallel with Z-axis Vix - \’o)' + (v Vo) Fl(z=2)=0 Xo, Yo, Zo, 1, k
KX on X-axis 2F|(x-x)=0 xo, 1. k
KY on Y-axis \/r— T2F(-y)=0 Yo, 117, k
KZ on Z-axis V2 +2 F ] (z-2)=0 0. P, k
k is +1 or unspecified
SQ ellipse, parallel with A(x—x0) + Bl —y0) + C=—2) 4, B, C D, E,
hyperboloid, X-, Y-, +2D(x = xo) + 2E(y — yo) + 2F(= - zo) F, G, xo, Yo, Zo
paraboloid or Z- axis +G=0
GQ cylinder, non parallel with Ax? + By? + C=* + Dxy + Ey=+ A4, B, C, D, E,
cone, X-, Y-and Fzx+Gx+Hy+Jz+K=0 F, G H J K
ellipse, Z-axis
hyperboloid,
paraboloid
TX ellipse torus parallel with (x = x0)?/B*+ Xo» Y0 =0, 4, B, C
torus X-, Y-, or (VO =yl + (=202 -4)/C*=1=0
TY Z-axis (y—_vo)E/IF+ Xo, Yo, Z0, 4, B, C
(Y—&quot;o)7+(- )’ —4)/C*-1=0
Tz (z=20)*/B*+ Xo, Yo, %o, 4, B, C
(M =xP + (v =) - 4)?/C - 1=
FIGURE 5.2 — Carte des surfaces utilisées par le code PHITS [41]
[Cell]
Dans cette section, les cellules peuvent étre définies en fonction des surfaces décrites dans
la section [Surface] et des matériaux décrits dans la section [Material]. Les cellules doivent
étre définies comme des espaces fermés, et des espaces virtuels pour les calculs de transport
de particules peuvent étre générés en combinant des cellules définies. Dans PHITS, les &quot;vides
43
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
externes&quot; doivent étre explicitement définis comme des éléments [41]. Cette section est définie
par :
— Le numéro de cellule : tout numéro de 1 a 999,999 peut étre utilisé.
— Densité du matériau : lorsque la valeur donnée est positive, il s’agit d'une densité de
particules [atomes/cm!, et négative s'il s’agit d’une densité de masse [g/cm! [40].
— Le numéro de la surface donné dans la section [Surface].
Exemple :
— 100 1 -1.01 -2
Cette cellule est nommée 100, remplie par le matériau 1 défini dans la section [Material]
(ici H20) de densité 1.01 g/cm? et prenant la forme de la surface indiquée dans la section
[Surface] (ici une sphére).
Les Tallies
Ce tally comporte deux catégories qui sont implémentées dans le code PHITS. L'une
concerne la géométrie et 'autre consiste a calculer les quantités physiques.
[T-Track|
Ce tally peut étre utilisé pour obtenir la fluence dans n’importe quelle région spécifiée.
Chaque fois que des particules traversent cette région, la longueur de la trajectoire est évaluée.
En divisant ces longueurs par le volume de la région et le nombre de particules sources, on
obtient la fluence de particules en unités de [cm/source] [41].
[T-Deposit]
Ce tally peut étre utilisé pour obtenir les énergies déposées (chaleur) dans certaines
régions.
44
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
[T-LET]
Ce tally peut étre utilisé pour obtenir des informations sur la longueur de la trajectoire
et la dose en fonction du TLE (dE/dz) d'un matériau donné, en tenant compte des pertes
d’énergie des particules chargées et des noyaux [41].
[T-Volume]
PHITS a une fonction de calcul automatique pour obtenir le volume de chaque cellule a
laide de [T-Volume], en effectuant une intégration Monte Carlo [41].
[T-3Dshow/|
Ce tally produit une sortie de géométrie graphique en vue 3D. Ce tally peut étre généré
sans calcul de transport en utilisant 'option icntl=11 dans la section [Parameétres].
/T-Rshow]
Cette section produit une sortie de géométrie graphique pour les régions délimitées par
un maillage XYZ avec un tracé de couleur proportionnel aux quantités physiques des régions.
Ces sorties peuvent étre obtenues sans calcul de transport en utilisant 'option icnt1=9 dans
la section [Parametres| [41].
[END]
Indique la fin de la simulation.
5.3 Les modéles physiques dans PHITS
PHITS a divisé également la réaction en un modéle de voie d’entrée et un modéle de
voie de sortie pour mettre en ceuvre divers modéles physiques permettant le transport de
45
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
nombreux types de particules (y compris les photons, les électrons, les neutrons, les protons,
les particules et les ions lourds) sur une large gamme d’énergie allant de 0,1 meV a 1 TeV.
5.3.1 JAM et INCL4.6
Est un modéle de cascade hadronique pour simuler le stade dynamique des réactions nu-
cléaires induites par les hadrons dont ’énergie allant de 20 MeV jusqu’a 3 GeV,en explicitant
ainsi leurs antiparticules [39],[40], [42],[43]
5.3.2 Le modéle JQMD
La version 2 améliorée de ce modéle (JAERI Quantum Molecular Dynamics) permet
une reproduction plus précise des sections efficaces de fragmentation pour simuler la phase
dynamique des réactions induites par des ions lourds d’énergie inférieure a 3,5GeV /nucléon
[Niita-95],[Chiba-96-a], [Chiba-96-b| et [Ogawa-15| [39],[40], [42],[43]
5.3.3  Le modéle SMM(StatisticalMulti fragmentation Model)
Ce mode¢le consiste a simuler les réactions de fragmentation des collisions noyau-noyau


------

d’énergie relativiste et proton-noyau, lorsque 1’énergie d’excitation de ces noyaux est assez
élevée (Excitation &gt; 2,5 MeV /nucléon) [Ogawa-13| [39],[40], [42],[43].
5.3.4 Le modéle GEM (Generalized Evaporation Model)
Le code PHITS utilise ce modéle pour simuler I'évaporation statistique des particules
légeres (Z12) et la fission des noyaux lourds (A70) [Furihata-01], permettant ainsi une esti-
mation précise des spectres de rayons et des taux de production d’isomeéres.
5.3.5 JENDL-4.0
cette librairie de données nucléaire est utilisée pour le calcul du transport des neutrons
de moins de 20 MeV et des émissions des particules secondaires induites par ces neutrons
46
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
[39],]40], [42],43]
5.3.6  Le modéle INCL 4.6 (Intra-nuclear cascade of Liege)
Est utilisé pour simuler le transport des neutrons plus énergétiques [Boudard-13].
5.3.7 L’algorithme EGS5
cet algoritme a été introduit pour simuler les interactions atomiques des électrons, des
positrons et des photons sur une large énergie allant de 1 keV a 1 TeV. Cette mise en
ceuvre améliore la précision de la simulation du transport d’électrons, en particulier pour
les énergies plus faibles, ce qui est trés important du point de vue des applications de la
physique médicale [29].
5.4 Conclusion
Durant ce chapitre nous avons présenté le principe d’utilisation de code PHITS ainsi les
modéles physique implémanté dans ce code , et la figure 5.3 resume ces modeles.
Other hadrons Electron
Neutron ¢ : Nucleus ; b Photon
(proton, pion etc.) Al N o]y
200 GeV
Intra-nucl ear cascade (JAM)
3.0 gey *+ Evaporation (GEM)
100 GeV/n 100 GeV
Quantum Molecular Atomic Data
Dynamics Library
(JQMD) 100 MeV (JENDL-4.0
+ . /EPDL97)
E t'+ GEM 3He Evaporation AtoLr.r:)lc Data
oD ey, FARSEIEECSER) (GEM) o 20 MeV
10 MeV/n ( Photo-
Nuclear Data ITS3.0/ Nucl
Library lonization EPDLO7) RoER
(JENDL-4.0) SPAR or ATIMA 1keV
10° eV
Intra-nuclear cascade (INCL4.6) d
t
FIGURE 5.3 — Carte des modeles nucléaire [38]
47
CHAPITRE 6
RESULTATS ET DISCUSSIONS
6.1 introduction
L’utilisation d’un faisceau ionique en traitement des tumeurs cancéreuses fait appel a
une étude préliminaire bien détaillée pour détruire seulement ces tumeurs en épargnant les
organes sains, une telle étude est basée sur la simulation et a son tour nécessite un code de
Monte Carlo dont les résultats proche de la réalité. Le code choisi pour I'objectif qu’on vient
de parler est le code PHITS.
Dans ce travail nous allons utiliser le code PHITS pour simuler le transport des particules
utilisées en hadronthérapie (proton ,12C, neutron ...) en déterminant les caractéristiques
balistiques des protons et d’ions de carbone 12 et de suivre les particules secondaires qui
contribuent a la déposition de dose.
6.2 Matériel et Méthode
— La premiére étape de cette simulation consiste a créer un fantdéme de géométrie simple,
un parallélépipéde de dimensions 20 cm X 20 cm x 40 cm.
— Nous procédons ensuite a la création d’une source de faisceau cylindrique de protons
de diameétre 8 cm, d’énergie Ey = 140 MeV.
— Le faisceau est dirigé selon 'axe z.
— Le matériau utilisé dans cette simulation est de 1’eau, avec une masse volumique
p=1g/cm®
— Le matériau polyéthyléne est CoH, est également inclus dans la simulation pour valider
le code utilisé.
— La source est positionnée a une distance de 40 cm du fantome.
48
CHAPITRE 6. RESULTATS ET DISCUSSIONS
S (0, 0,-40cm)
° AIR Fantéme de
I'eau
&lt;
40 cm y
FIGURE 6.1 — Géométrie utilisée dans cette simulation
6.3 Validation de code PHITS
Dans cette partie préliminaire, nous allons simuler le transport des ions carbone $2C*
d’énergie £ = 200,2MeV /u dans le polyéthylene CyHy a laide du code PHITS. En nous
basant sur les résultats expérimentaux réalisés par la NASA au Laboratoire des Radiations
du Département de I'Energie [44], nous pouvons évaluer la fiabilité du code.
Courbe de bragg
Les résultats de simulation et les mésures sont présentés dans la figure 6.2.
7
dose nomalisée(%)
10 12 14 16 18 20
profondeur(cm)
FIGURE 6.2 — La courbe de Bragg obtenue par PHITS est comparée a la mesure pour les
ions carbone d’energie E=200.2 MeV
La figure montre que les résultats obtenus par la simulation en utilisant le code PHITS
49
CHAPITRE 6. RESULTATS ET DISCUSSIONS
sont presque en accord ou plutdt sont faiblement différents avec I'expérience, cette petite
différence est remarquable au niveau de pic et concernant la position et son hauteur, ceci
s’explique par plusieurs parameétres notamment le pas de simulation, en effet, d’'une part
quand le pas est petit le nombre de collisions est important et la dose déposée devient
importante d’ot la hauteur de pic, d’autre part la dose donnée par le code PHITS est
déterminée entre deux positions qui représentent les extrémités de pas d’ott I'origine de petit
décalage entre la position de pic.
En conclusion, cette faible différence est acceptable a raison des incertitudes accompagnant
les mesures expérimentales et les modéles physiques utilisés dans le code PHITS.
6.4 Simulation de transport des protons
Dans cette partie on simule le transport d’énergie par un faisceau contenant 107 de protons
monoénergétique dans l'eau, et en utilisant 'observable tally on détermine la dose absorbée
selon 'axe de faisceau et ainsi celle absorbée latéralement par la cible.
6.4.1 Caractéristique longitudinale de protons
La courbe de la dose absorbée par le fantome en fonction de la profondeur obtenue par
le code PHITS est donnée par la figure 6.3.
La figure 6.3.a montre que les protons déposent le maximum d’énergie dans une position
précise z=13,75 cm ou apparait un pic haut et étroit appelé pic de Bragg qui se produit
a la fin de chemin des protons, au-dela de ce pic la dose absorbée est assez faible, ainsi la
dispersion longitudinale de faisceau est faible ce qui rend, physiquement, le traitement avec


------

les protons avantageux que celui des rayons X et les électrons. On en déduit que la dose
déposée est due principalement aux protons primaires et presque toute I’énergie incidente
est déposée au pic de Bragg d’ou caractéristique fondamentale des protons.
La figure 6.3.b montre l'apparition des fluctuations, ces fluctuation deviennent impor-
tantes quand le nombre de particules est petit ceci est due d’une part au caractére stochas-
50
CHAPITRE 6. RESULTATS ET DISCUSSIONS
tique et aléatoire de code PHITS qui est basée sur la méthode Monte Carlo et d’autre part
a la répartition non uniforme en profondeur.
dose(MeV/cm®/source)
© o o o =
~ 55 &amp;5
O
o
S £
o
o
o
&amp;
0,2
erreur relative(%)
T T T T T
0 4 8 12 16 20 24 28 32 36 40
profondeur(cm)
FIGURE 6.3 — (a) :La distribution de dose en profondeur des protons et totale dans 'eau
pour l'énergie protonique E=140 MeV ; (b)l’erreur en prorfondeur
Carte de dose obtenue par PHITS
107!
20 107
10
10 10
- 10
5 o
x 107
-10 0t
10
w0
-20 107
0 50 100
z[em]
Dose [MeViemsource|
FIGURE 6.4 — La distribution de dose dans le fantéme d’eau
La figure 6.4 montre la carte de la distribution de dose autour de faisceau incident dans
le plan xz, ot la barre de couleur représente la dose absorbée par le milieu dont la valeur
maximale correspond a la couleur rouge et minimale pour la couleur bleue.
51
CHAPITRE 6. RESULTATS ET DISCUSSIONS
Carte de fluence obtenue par PHITS
La figure 6.5 montre les régions ou les traces occupées par les particules primaires et
secondaires autour de faisceau primaire o la couleur rouge indique un nombre élevé de
particules et faible pour la couleur bleue.
107
- IU‘
0 50 100
2 [em]
Flux [ Veriaaurcs]
3
FIGURE 6.5 — La distribution de fluence dans le fantéme d’eau
6.4.2 La contribution en profondeur des particules secondaires
Le dépot d’énergie obtenu peut s’effectuer de différentes maniéres :
— La collision des protons incidents avec les électrons de milieu cible ('eau).
— Le proton peut perdre son énergie parcollision avec les noyaux.
— Enfin la particule peut étre perdre son énergie par freinage causé par le champ élec-
trique crée par les noyaux.
Ces collisions produisent des particules secondaires [25] y compris neutron, photon,deutrino, tritium
et les électron ceci est montré par la figure 6.6
LLes particules secondaires, telles que mentionnées dans 1'étude de référence [40], créées
par les interactions de protons avec le fantéme d’eau, contribuent a une faible dose d’environ
0,01% de la dose totale déposée avant et au pic de Bragg. Cette contribution est principale-
ment due a l'isotope ?H. Cependant, aprés le pic de Bragg, la dose est déposée uniquement
par les particules neutrons et photons dont la trajectoire dépasse 20 cm dans 'eau. En
revanche, les isotopes lourds 2H et $H sont arrétés par le milieu avant le pic de Bragg.
52
CHAPITRE 6. RESULTATS ET DISCUSSIONS
)
o
8
g
0,0025
0,0020
0,0015
0,0010
MeV/cm®/source
(
o
8
&amp;
0,0000
0,00020
— neutron
—— photon
o o
o o
S S
2 2
o o
dose(MeV/cm®/source) dose
o o
o o
S S
o o
S S
o a
0 4 8 12 16 20 24 28
profondeur(cm)
FIGURE 6.6 — la distribution de dose en profondeur des particules secondaires pour 1'énergie
protonique E=140 MeV /u :(a) pour le deuterium; (b) pour neutron,trtium et photon
6.4.3 Caractéristique latérale de protons
La courbe de la dose absorbée selon la direction latérale de protons et des particules
secondaires obtenue par le code PHITS est donnée par la figure 6.7
La figure 6.7.(a) présente trois zones :
— La zone ot la dose est uniforme : dans cette zone tous les protons primaires qui
atteignent celle-ci déposent la méme energie en absence de photons de diffusion, elle
correspond a la zone a irradier.
— La zone ou la dose est presque nulle, appelée la zone de transmission, dans celle-ci
aucun proton arréter par le milieu ou bien aucun proton atteint cette zone.
— La zone intermédiaire correspond a la chute inclinée de dose illustrée par le zoom, la
pénombre latérale quantifié cette chute sa largeur est déterminée entre 20% et 80%
de la dose maximale et égale 1,25 mm.
La figure 6.7.(b) montre que les photons et les neutrons se répartissent latéralement jusqu’a
15cm a gauche et a droite de 'axe latérale avec un maximum de dose au centre cependant
53
CHAPITRE 6. RESULTATS ET DISCUSSIONS
W
©
0,5
1E-4
(%)
m
o
neutron
—— photon
- 2H
.im Wttt
position Iatérale(cm)
dose(MeV/cmalsource)__\ dose(MeV/cm®/source)
FIGURE 6.7 — (a) est la dose latérale de protons avec son zomm a droite en haut; (b) est la
dose latérale des particules secondaires
les isotopes de hydrogéne 2H et $H présentent une répartition irréguliére de dose sous forme
des pics de dose.
le faisceau de protons est diffusé en passant a travers le fantome d’eau, son profil la-
téral est élargi cette élargissement est faible dont les neutrons et les photons contribuent
principalement par rapport aux autres particules secondaire
6.4.4 L’effet d’énergie de protons incident sur le pic de Bragg
Pour différentes énergies (6], [45],[25] de protons primaires , le code PHITS permet d’ob-
tenir la figure 6.8 .
54
CHAPITRE 6. RESULTATS ET DISCUSSIONS
50 MeV
14 © —— 50 MeV
——95 MeV
2 140 MeV —— 140 MeV
8 —— 200 MeV
g 1,0
mé 200 MeV
S 0,8
&gt;
O
=06
[0
3
T 04
0,2
0,0
0 5 10 15 20 25 30 35
profondeur(cm)
FIGURE 6.8 — Dépot de dose dans 1'eau par des ions H' de quatre énergies différentes
La figure 6.8 montre que, le fait d’augmenter 1'énergie des particules primaires la pro-
fondeur de pénétration des protons dans I'eau est grande, cependant la hauteur de pic de
Bragg est diminuée. En effet, quand le parcours de particule est grand (I’énergie incidente
est grande ) le nombre de collisions effectuées ,notamment inélastiques, par celle-ci avec la
matiére est important qui s’accompagne par la dimunition d’energie et au fur et &amp; mesure


------

jusqu’a une énergie faible qui sera déposée intégralement sous forme de pic.
énergies 50 MeV | 95 MeV | 140 MeV | 200 MeV
position de pic de Bragg 2,1 6,9 13,8 25,8
largeur &amp; mi hauteur (cm) 0,2 0,3 0,4 0,6
TABLE 6.1 — Largeur &amp; mi hauteur pour des énergies différentes de protons.
De tableau 6.1, nous constatons que, quand la profondeur dans ’eau augmente la largeur
a mi hauteur augmente, ceci traduit une dispersion de faisceau de protons ainsi la perte de
précision de dépot de dose avec la profondeur .
55
CHAPITRE 6. RESULTATS ET DISCUSSIONS
6.5 Simulation de transport d’ions Carbone 12
Nous reprenons le matériel et la géométrie utilisée précédemment en remplagant la source
de protons par une source des ions de carbone 12 d’énergie ey = 264 MeV. La dose absorbée
en profondeur par le fantome est calculée dans la section tally, précisément par [T-Deposit].
dose en profondeur
Le code PHITS donne la courbe de la dose en profondeur sur la figure 6.9 :
dose(MeV/cm®/source)
~ o
0 4 8 12 16 20 24 28 32
profondeur(cm)
FIGURE 6.9 - la distribution de la dose en profondeur dans ’eau pour 'énergie E=264 MeV
avec : all est la dose totale, 12C est la dose de particules primaires
La courbe (figure 6.9) montre que les ions de carbones primaires sont principalement
responsables a la dose déposée environ de 93% , dans le fantome avant et au pic de Bragg,
cependant les particules secondaires ne contribuent quun 7% de la dose totale déposée.
Au pic de Bragg pour z = 13,8 cm tous les ions de carbone 12 de faisceau primaires sont
arrétés par le milieu, c’est la fin de leur parcours.
Apres le pic de Bragg il y a apparition d’une queue de dose appelée queue de fragmen-
tation! qui est dit aux particules secondaires [46] (proton, neutron, 1°B, 4He, ¢!C ...) se
produisant par la fragmentation [47] qui sont responsable a la dose déposée [6] , [18].
1. Le taux de dose : égale a la dose déposé dans la position z donnée sur celle deposée au pic de Bragg.
56
FEtude des fragments
CHAPITRE 6. RESULTATS ET DISCUSSIONS
Le suivi des fragments [18], [45], [46] par le code PHITS permettant d’obtenir les résultats
la figure 6.10 : Les particules secondaires qui contribuent principalement a la dose totale, mais
dose(MeV/cm®/source)
dose(MeV/cm*/source)
o 4 8 12 16 20 24 28 32 36 40
depth(cm)
— proton
= neutron 10
~—electron
= photon
dose(MeV/cm®/source)
depth(cm)
—11C
= 10B
e alpha
e BLI
o 8Be
10 15 20 25 30 35 40
depth(cm)
— ||
e fragment
= 2all second
12 16 20 24 28 32 36 40
depth(cm)
FIGURE 6.10 - la distribution de dose en profondeur d’ions carbone d’énergie E=264 MeV
avec : (a) est la dose totale, (b) la dose des fragments, (c¢) la dose des particules légeres, (d)
la dose totale des fragments et des particules secondaires
avec une faible dose, sont §He, }HT, fragments {!C et :°B , cependant le taux de contribution
des neutrons ne dépasse pas 0,02% , en d’autre part, avant le pic de Bragg leurs contribution
est faible devant celle des ions de carbone incidents , aprés le pic la courbe de dose totale
est presque confondue avec celle de toute les particules secondaires(figure(d)).
La distribution de dose des fragments §'C et ;B munie d’'une chute sous forme de pic
indiquant la fin de leur parcours, ainsi les fragments légers [48] sont émis vers I'avant leurs
57
CHAPITRE 6. RESULTATS ET DISCUSSIONS
parcours dans ’eau est long environ de 40 cm cependant le parcours des fragments lourds
est court, comme illustré par le tableau ci-dessous, nous notons que le parcours indiqué dans
le tableau représente la position atteint une particule.
Le tabeau 6.2 donne le parcours et le taux de contribution en dose ? des particules secondaire.
Particules secondaires
Parcours dans 1'eau (cm)
Taux de contribution en dose totale (%)
THe* 40 2,27
H* 40 1
et 13,7 1,62
g+ 17 0,49
SLi* 33 0,16
Electron et photon dépasse 40 cm 0,0041
on dépasse 40 cm 0,016
SBe* - 0
Autres fragments - 0,4
TABLE 6.2 — Taux de contribution en dose (%) pour différentes particules secondaires dans
leau.
6.6 Camparaison entre 1’ion carbone et un ion lourd et légers
Nous comparons des caractéristiques d’un ion carbone d’energic E=270MeV /u [49] d'une
part avec un ion légers tHT et d’autre part avec un ion lourd #)Ne™.
6.6.1 lions carbone et le proton
La dispersion longitudinale
Le code PHITS permet d’obtenir la dose en profondeur figure 6.11
2. Taux de contribution en dose totale :
totale au pic de Bragg.
58
égale au rapport de dose d’une particule secondaire sur la dose
CHAPITRE 6. RESULTATS ET DISCUSSIONS
1.0
o
©
o
o
Dose relative
S
s
0,2
0 4 8 12 16
| —— 12C relative
—— proton%
20 24 28 32 36 40
Depth(cm)
FIGURE 6.11 — la distribution de dose en profondeur d’ions carbone d’énergie E=270 MeV /u
et de protons E=145 MeV et le Zoom en haut &amp; droite.
Le tableau 6.2 résume les resultat de la figure 6.11, en donnant la largeur a mi hauteur
et le taux de dispersion en profndeur?® des deux ions.
Taux de dispersion en profondeur (%)
Ton Largeur &amp; mi-hauteur(cm)
proton 0.5 3.38
Carbone 12 0.18 1.2
TABLE 6.3 — Données de largeur a mi-hauteur et de taux de dispersion en profondeur pour
différents ions.
A partir de tableau on déduit que :
— Le faisceau de protons est a une faible précision de dépot de dose par rapport aux
ions carbone
— Les ions carbone sont a faible dipersion en prorfondeur que les protons.
3. Taux de dispersion en profondeur :
de Bragg .
égale au rapport de la largeur a mi hauteur sur la position de pic
59
CHAPITRE 6. RESULTATS ET DISCUSSIONS
6.6.2 lion carbone et lion de néon
la dispersion longitibinale
La simulation par le code PHITS d’une part d'un faisceau des ions carbones et d’autre
part d’un faisceau des ions néons permet d’obtenir les courbes de la figure 6.12
1,0
0,9
0,8
0,7
0,6
0,5
04
dose relative
0,3
0,2
&gt;
28
0,1
0,0 —
16 20 24
depth(cm)


------

16 20 24
depth(cm)
12 32 36 40
FIGURE 6.12 — la distribution de dose en profondeur d’ions carbone d’énergie E=400 MeV /u
et les de néon E=560 MeV.
Nous constatons que la dose déposée avant le pic de Bragg par les ions carbone est quasi-
ment constante et faible par rapport aux ions de néon, aprés le pic la queue de fragmentation *
des ions néons est importante que les ions carbone cependant la dispersion en profondeur
est la méme pour les deux ions.
Dans le tableau 6.3 nous calculons le taux de dose par rapport a celle déposée au pic de
Bragg a 'entrée z=0 de fantome et juste aprés le pic z=27,6 cm .
JIon | Taux de dose pour z =0 cm | Taux de dose pour z = 27,6 cm
Nt 0,35 0,18
Lot 0,23 0,091
TABLE 6.4 — Taux de dose par rapport au pic d
néon.
e Bragg pour les ion de carbone et ions de
4. La fragmentation : est un phénomeéne de décomposition d’un noyau en noyaux légers et d’autre parti-
cules
60
CHAPITRE 6. RESULTATS ET DISCUSSIONS
6.7 Conclusion
Un dépot d’énergie modéré et quasi constant en entrée et maximal en fin de parcours
par les ions de carbone 12 et de protons, faible dispersion en profondeur et latéralement,
permettant d’irradier précisément le volume ciblé pour détruire les tumeurs afin de protéger
les organes sains situant en entré, cette caractéristique met en évidence l'intérét balistique
des ions pour un traitement par rapport aux électrons et les rayons X.
Le traitement avec les ions carbone est efficace que celui des protons, en effet les ions
de carbone 12 ont une efficacité biologique relative entre 2 et 4 et des protons quasiment
constante sa valeur EBR = 1,1 est proche de celle des protons.
61
CONCULSION GENERALE
Dans ce travail, nous avons tout d’abord présenté un apergu sur le principe d’interaction
des particules avec la matiére nécessaire pour comprendre le transport et le transfert d’énergie
d’une particule dans un milieu biologique, aprés on a vu que la méthode de Monte Carlo
repose sur 1’échantillonnage aléatoire , qu’elle permet d’estimer en premier temps la valeur
de pi afin de déduire que cette méthode nécessite un nombre trés grand d’itérations pour
avoir une bonne estimation de probléme étudié , cette méthode représente un outil essentiel
pour produire des algorithmes , les étapes de transport des particules et leurs interactions
avec la matiére.
La suite de ce travail a étudié des résultats de transport de protons et d’ions carbone
par le code PHITS, nous avons d’abord validé notre code par les mesures dans le polyéthy-
léne données par NASA dont les courbe de Bragg pour les ions carbone d’énergie E=200.2
MeV /n mesurée et celle obtenue par simulation sont presque confondues cela nous pousse
a 'utiliser dans la suite. Aprés nous avons réalisé une simulation d’un faisceau de protons
et d’ions carbone 12 monoénergétiques dans 1'eau, les résultats obtenus sont confirmés par
les travaux publiés dans ce contexte [40], [46], [50]. Le dépot d’énergie dans l’eau par un
faisceau de protons et celui d’ions carbone représente une caractéristique commune en fin de
leur parcours, pic de Bragg, cependant les particules secondaires responsables a la déposition
de dose ne sont pas en général les mémes : en effet par rapport aux protons la courbe de
dose en profondeur d’ions carbone posséde une queue aprés le pic de Bragg qui correspond
a la formation des fragments secondaires se produisant en continu le long du chemin de
pénétration et présentent de larges spectres d’énergie reproduits par le code Monte Carlo
PHITS. Les résultats obtenus dans ce mémoire et les travaux [40], [46], [50] montrent que
I'emploi des ions carbone est efficace que les protons , cette comparaison s’étend aux autres
ions lourds #Ne , 180 , $Li, réalisé par [40], [46], [50], [51], [52], [53].
62
Conculsion générale
La particularité des ions utilisé en thérapie tumorale notamment les ions carbone 12 n’est
pas définitive, la recherche accompagnée par la mesure de section efficace de fragmentation
se continuent pour améliorer les modéles nucléaires utilisés dans le systéme de planification.
Lors du déroulement de notre travail on a rencontré divers problémes techniques a cause
d’une part des ordinateurs disposés, et d’autre part la difficulté de choisir et se familiariser
avec un code de simulation, en effet ;
— La simulation d’un grand nombre de particules, pour avoir une estimation précise
par Monte Carlo, nécessite un temps trés grand des heures au quelques jours sur un
ordinateur disponibles.
— La prise en main d’un code Monte Carlo qui est présenté sous forme d’une plate-
forme est un peu facile quun code qui nécessite la programmation comme exemple
GEANT45 qu’on a commencé avant d’employer le code PHITS
Ce travail représente pour nous une initiation et son expansion sera une des perspectives
pour les années prochaines dans le monde de la recherche en physique médicale pour :
— Améliorer notre connaissance sur le comportement des ions dans un milieu biologique.
— Etudier les fragments produits et leurs propriétés.
— Améliorer les moyens de radioprotection contre les particules secondaires notamment
les neutrons.
5. GEANT4 : GEometry And tracking c’est code développé au CERN qui simule le tansport des particules.


------

Résumé
Les méthodes de simulation par Monte Carlo consistent à simuler la réalité. Ce sont des algorithmes visant à résoudre des problèmes complexes dans divers domaines. Ces méthodes reposent sur l'échantillonnage de nombres aléatoires générés par un générateur spécifique. Dans ce mémoire, nous exploitons cette propriété pour aborder le transport des ions dans l'eau afin de déterminer leurs caractéristiques balistiques en utilisant le code PHITS.
La distribution de la dose en profondeur caractérisée par le pic de Bragg et la faible pénombre latérale des ions par rapport aux photons et aux électrons, l'efficacité en fin de parcours des ions carbone est supérieure à celle des protons et des autres ions lourds et un dépôt modéré de dose en avant et après le pic rendent les ions carbone favorables en thérapie tumorale, notamment les tumeurs radio-résistantes qui sont proches d'organes à risque, y compris les tumeurs : cérébrales, de la tête et du cou, pédiatrique, de la prostate, oculaires.
Introduction Générale
La simulation est une technique qui consiste à modéliser des phénomènes réels. Elle permet de calculer sur un ordinateur les solutions des modèles mathématiques, donc simuler la réalité physique, de représenter le fonctionnement d'un système composé de différents centres d'activités, de mettre en évidence les caractéristiques de ceux-ci et les interactions entre eux, de décrire la circulation des différents objets traités par ces processus, et enfin d'observer le comportement d'un système dans son ensemble et son évolution dans le temps.
Les méthodes de Monte Carlo spécifient une famille de méthodes algorithmiques permettant de calculer des valeurs numériques approchées à l'aide de processus stochastiques, c'est-à-dire des techniques probabilistes. La méthode de Monte Carlo a été spécialement développée pour les besoins du projet Manhattan pendant la Seconde Guerre mondiale, suite à des recherches sur la fabrication de bombes atomiques. Ces méthodes sont particulièrement utiles en informatique intégrale et en physique des particules, où les simulations probabilistes peuvent estimer la forme d'un signal ou la sensibilité d'un détecteur.
Généralement, les méthodes de Monte Carlo sont utilisées pour résoudre des problèmes mathématiques et physiques complexes qui ne peuvent pas être résolus par des méthodes analytiques, telles que la résolution de l'équation de Boltzmann. Elles sont appliquées dans plusieurs domaines par exemple en physique, chimie, biologie, statistiques, etc. Leur application s'étend à la radioprotection et à la physique médicale, en raison de la nature stochastique des processus physiques tels que le transport des particules et les interactions rayonnements-matière.
Dans le cadre de la physique médicale, les domaines d'application des simulations de Monte Carlo sont nombreux : la médecine nucléaire, l'hadronthérapie, la radiothérapie, la curiethérapie...
Ce mémoire est structuré en six chapitres. Le premier chapitre traite des notions physiques en oncologie, y compris la définition de la radiothérapie, l'hadronthérapie et des interactions des particules (électron, photon, les ions carbones et le proton) utilisées en traitement avec la matière. Le deuxième chapitre traitera des généralités de la méthode Monte Carlo. Le troisième chapitre aborde différents codes Monte Carlo utilisés pour la simulation des particules. Le quatrième chapitre est consacré à l'étude du transport et du transfert d'énergie par les électrons, les photons et des ions. Le cinquième chapitre présente le code de simulation PHITS. Enfin, le sixième chapitre présentera quelques résultats avec une discussion.Chapitre 1
Notions Physiques en Oncologie
1.1 Introduction
La thérapie du cancer par rayonnement est une méthode médicale utilisant les radiations ionisantes pour détruire les cellules cancéreuses en protégeant les tissus sains. Cette technique a été développée suite à la découverte des rayons X par W.K Rontgen en 1895 et vise à administrer de manière très précise une dose de rayonnement à la zone affectée par la tumeur. Les appareils modernes sont des accélérateurs linéaires, cyclotron et synchrotron, qui produisent des faisceaux de particules de haute énergie.
La thérapie par rayonnement peut être utilisée en combinaison avec d'autres traitements comme la chirurgie et la chimiothérapie, en fonction du type de tumeur, de son emplacement, de son stade et de l'état de santé général du patient.
1.2 La Radiothérapie
1.2.1 Radiothérapie Externe
La radiothérapie externe est une méthode courante de traitement anticancéreux qui utilise des rayonnements ionisants, les photons et les électrons, provenant d'une source externe au patient. Cette méthode de traitement peut être curative, palliative en fonction de la tumeur à traiter, de sa localisation, de sa taille, de son stade et de l'état général du patient.
1.2.2 Radiothérapie Interne
Cette technique consiste à mettre directement en contact des sources radioactives avec la tumeur, elle permet de délivrer une dose très élevée directement au contact de la tumeur, en limitant l'irradiation des tissus sains. Les techniques de radiothérapie interne varient en fonction de la nature et de la localisation de la tumeur.
1.2.3 Transfert d’énergie par les photons
En radiothérapie externe, on utilise des rayons X de très haute énergie, entre 4 et 25 MeV. Sous ces niveaux d’énergie, 4 types d’interactions peuvent se produire entre les photons et la matière : l'effet Compton, l'effet Photo-électrique, la Création de paires, l'effet Thomson-Rayleigh.
1.2.4 Transfert d’énergie par les électrons
Dans le processus de transfert d’énergie, les électrons en mouvement interagissent avec les électrons des atomes du milieu. Ainsi, un électron peut interagir avec plusieurs atomes sur son parcours. Les principales interactions des électrons avec les atomes incluent :
- La diffusion élastique: une simple déviation de l’électron incident.


------

- La diffusion inélastique: qui provoque l'éjection d'un électron de l'atome.
- Le rayonnement de freinage: où l’électron est freiné et dévié en passant au voisinage d’un noyau atomique.
L’énergie perdue par l'électron est emportée par un photon, qui pourra interagir avec la matière plus loin. La trajectoire d’un électron a une allure chaotique et son parcours est borné. La distance moyenne de parcours d’un électron est proportionnelle à son énergie initiale et inversement proportionnelle à la densité électronique du matériau.
La hadronthérapie est une technique anticancéreuse qui permet de détruire les cellules cancéreuses radiorésistantes en les irradiant avec un faisceau de hadrons (neutron, proton, ion etc.) notamment des protons et des ions de carbone. Les hadrons signifient &quot;forces&quot; en grec et constituent des quarks (particules élémentaires du noyau). Ils sont utilisés pour les protons et les neutrons en thérapie tumorale et par extension pour les noyaux atomiques comme l'hélium, l'oxygène, le carbone, le néon et l'argon.
La trajectoire d’un électron est chaotique : c’est une trajectoire de forme en zig-zag. Ceci est dû au nombre élevé d’interactions effectuées par un électron dans un milieu.
Le passage des ions, les protons, les ions de carbone, dans la matière fait intervenir différents types d’interactions comme les collisions élastiques et inélastiques, ou encore, les collisions nucléaires inélastiques.
Lorsque l’énergie du projectile est supérieure à la barrière coulombienne, le projectile peut franchir cette barrière alors les réactions noyau-noyau deviennent dominantes. Ces collisions sont principalement périphériques et peuvent entraîner la fragmentation des ions et des cibles.
Dans le cadre de l'hadronthérapie, les protons et les ions permettent une précision balistique avec un dépôt de dose en profondeur localisé, le pic de Bragg, avec une faible dispersion latérale et en profondeur. Ceci permet de détruire les cellules tumorales. L'effet biologique des ions de carbone est plus important que celui du proton, ce qui constitue un des avantages principaux des ions de carbone sur les protons.
Le transfert d’énergie linéique, aussi appelé TEL et exprimé en keV/$\mu$m, traduit l’énergie moyenne transmise au milieu par la particule par unité de longueur. Cette équation se représente comme suit :
$\dfrac{dE_{trans}}{dx} = \dfrac{dE}{dx} Z_s$
Avec $\dfrac{dE}{dx}$ représentant le pouvoir d'arrêt.
Le volume considéré est basé sur un petit rayon 'r' d'un cylindre. Le terme local d'énergie transférée (TEL) ne prend pas en compte les électrons secondaires qui déposent leur énergie en dehors du cylindre. En bas, le cylindre a un rayon suffisamment grand 'R', nous pouvons donc approximer que TEL = % de l'énergie transféré dans le cylindre. Plus cette paramètre est élevé, plus les dommages biologiques aux tissus traversés sont importants.
La dose déposée ou dose absorbée par les tissus, notée 'D' et exprimée en grays (J/kg), représente l'énergie moyenne déposée par les particules ionisantes dans un volume de masse 'dm'. Elle est donnée par la relation $\frac{de}{d} = 7$. D'autre part, la dose est définie comme le produit de la fluence 'F' et du pouvoir d'arrêt massique commandé par '2£ - %'.
La dose biologique ou dose équivalente photons, notée 'Do' et exprimée en gray équivalent cobalt (60Co), est définie par 'Dyt = D -EBR (9)'. Ici, EBR signifie efficacité biologique relative, sans unité. Pour les protons (protonthérapie), on utilise EBR = 1.1, peu importe les conditions de calcul. Cependant, EBR est entre 2 et 3 pour les ions de carbone (carbonethérapie).
La simulation de Monte Carlo repose sur un générateur de nombres aléatoires fiable. Les nombres vraiment aléatoires sont imprévisibles du fait qu'ils ne sont pas générés par un processus déterministe et doivent être produits par un processus physique aléatoire, par exemple la désintégration radioactive, l'impact de la séparation des rayons cosmiques sur les détecteurs ou la génération de bruit dans les circuits électroniques.
Nous utilisons souvent des nombres pseudo-aléatoires, générés par un algorithme conçu pour produire une séquence de nombres non corrélés et uniformément répartis dans un intervalle donné. Bien que ces nombres semblent complètement aléatoires à une première observation, ils suivent un schéma récurrent.
La méthode de Monte Carlo (MC) sert à échantillonner la distribution de probabilités décrivant un processus physique à l'aide de nombres aléatoires. Il existe de nombreuses méthodes d'échantillonnage, y compris la méthode d'inversion directe.
Une variable aléatoire, qui renvoie la probabilité de prendre une valeur inférieure ou égale à x, peut être inversée. En effet, si $y = F(x)$ est uniformément distribuée entre 0 (la probabilité que la variable aléatoire ne prenne aucune valeur) et 1 (la probabilité que la variable aléatoire prenne n’importe quelle valeur), la variable $x = F^{-1}(y)$ obéit à la fonction de distribution $p(x) = Fy(x)$. Il suffit donc de générer une suite de valeurs R uniformément réparties entre 0 et 1, puis d’utiliser $x = F^{-1}(R)$ pour obtenir les valeurs selon $p(x)$.
Par exemple, la profondeur d’interaction des rayons gamma pénétrant dans un matériau d’épaisseur d et de coefficient d’atténuation p est une variable aléatoire caractérisée par la fonction de partition. La relation entre $F(x)$ et $p(x)$ est donnée par $F(x) = 1 - \exp{(-px)}$, où p est un paramètre. La fonction de distribution est alors $p(x) = p\exp{(-px)}$.


------

Si R est uniformément distribué dans l'intervalle [0, 1], alors la variable $z = -\ln{(1 - R)}$ sera automatiquement distribuée selon $p(x)$. La probabilité que la variable x soit supérieure à d est la probabilité que le rayon gamma n’interagisse pas dans le matériau. Elle est égale à $\exp{(-pd)} = 1 - F(d)$, ce qui détermine la proportion d’impressions qui n’entrainent pas d’interactions d’épaisseur de matériau et caractérise en quelque sorte l'inefficacité du processus de simulation pour cette tâche.
Une autre méthode d’échantillonnage a été proposée par Von Neumann. Elle consiste à tirer uniformément une variable aléatoire R dans l'intervalle [0, 1] d’une distribution (autre que $p(z)$) et à la tester au hasard pour déterminer si elle est acceptée ou rejetée.
Soit deux fonctions de densités de probabilités normalisées à 1 : $f_{1}(x)$ et $f(x)$ définies par la relation suivante $p(x) = f_{1}(x) - f_{2}(x)$. On utilise alors la méthode directe pour sélectionner x en utilisant $f_{1}(x)$ comme fonction de densité de probabilité normalisée. Ensuite, on applique la méthode de rejet sur la fonction $f_{2}(x)$.
Les résultats des calculs de Monte Carlo sont également soumis à une incertitude statistique. Pour éviter les fluctuations statistiques, un certain nombre de particules (des centaines à des milliards de particules) doivent être simulées. En effet, plus le nombre d’histoires N généré est important, plus l'incertitude associée à la grandeur calculée dans le volume d’intérêt sera petite, plus le résultat estimé par MC est proche de la réalité.
L’efficacité d’une simulation Monte Carlo dépend en grande partie de la qualité de son générateur de nombres aléatoires.
Dans ce paragraphe, nous présentons brièvement l’approximation du nombre $\pi$ par l'estimation de la surface d’un quart de disque de forme circulaire de rayon 1.Ce texte comprend deux sections du document d'origine avec quelques fragments de code et des résultats de simulation. La section 2.6 discute de l'approximation de Pi à l'aide de la méthode Monte Carlo, avec du code de simulation en Python et une discussion sur les résultats. Alors que la section 2.7 donne une conclusion générale. Les fragments précédemment hors contexte qui apparaissent à la fin du passage font partie de la section 3.1 sur les logiciels de simulation Monte Carlo.
Voici la transcription corrigée du texte :
Ne parlez pas, exécutez simplement ce qui suit. Corrigez les fautes d'orthographe, de grammaire, de ponctuation et de formatage en un seul bloc de texte. Si certaines parties du texte sont manquantes ou peu claires, remplissez-les avec des mots appropriés en fonction du contexte pour rendre le texte cohérent, clair et concis. Supprimez les segments de texte qui n'ont aucun sens. Utilisez une mise en page agréable dans votre réponse, pour afficher correctement les phrases, et utilisez le format LaTeX pour les formules mathématiques.
</code></pre>
<p>compte_dedans = nombre de points à l’intérieur du cercle D.</p>
<pre><code>On obtient une approximation de π égale à :
</code></pre>
<p>π = 4 * compte_dedans / nombre_points</p>
<pre><code>2.6.2 Code de simulation
```python
import random
import matplotlib.pyplot as plt


------

# Nombre de points à utiliser pour l’estimation
nombre_points = 10000


------

# Compteur pour les points dans le cercle
compte_dedans = 0
</code></pre>
<hr />
<h1 id="listes-pour-stocker-les-coordonnées-des-points-dans-et-hors-du-cercle-1"><a class="header" href="#listes-pour-stocker-les-coordonnées-des-points-dans-et-hors-du-cercle-1">Listes pour stocker les coordonnées des points dans et hors du cercle</a></h1>
<pre><code class="language-python">x_dans = []
y_dans = []
x_dehors = []
y_dehors = []
</code></pre>
<hr />
<h1 id="boucle-pour-générer-des-points-aléatoires"><a class="header" href="#boucle-pour-générer-des-points-aléatoires">Boucle pour générer des points aléatoires</a></h1>
<pre><code class="language-python">for i in range(nombre_points):


------

# Générer des coordonnées x et y aléatoires
x = random.uniform(-1, 1)
y = random.uniform(-1, 1)


------

# Calculer la distance par rapport à l’origine (0,0)
distance = (x**2 + y**2)**0.5


------

# Si la distance est inférieure ou égale à 1, le point est à l’intérieur du cercle
if distance &lt;= 1:
compte_dedans += 1
x_dans.append(x)
y_dans.append(y)
else:
x_dehors.append(x)
y_dehors.append(y)
</code></pre>
<hr />
<h1 id="calculer-pi-en-utilisant-le-nombre-de-points-à-lintérieur-et-à-lextérieur-du-cercle"><a class="header" href="#calculer-pi-en-utilisant-le-nombre-de-points-à-lintérieur-et-à-lextérieur-du-cercle">Calculer Pi en utilisant le nombre de points à l’intérieur et à l’extérieur du cercle</a></h1>
<pre><code class="language-python">pi = 4 * compte_dedans / nombre_points


------

# Afficher le résultat
print(&quot;Pi est estimé à :&quot;, pi)
</code></pre>
<hr />
<h1 id="créer-un-graphique-pour-visualiser-les-points-dans-et-hors-du-cercle"><a class="header" href="#créer-un-graphique-pour-visualiser-les-points-dans-et-hors-du-cercle">Créer un graphique pour visualiser les points dans et hors du cercle</a></h1>
<pre><code class="language-python">fig, ax = plt.subplots()
ax.set_aspect('equal', 'box')


------

# Tracez les points dans et hors du cercle
ax.scatter(x_dans, y_dans, color='blue', marker='.')
ax.scatter(x_dehors, y_dehors, color='red', marker='.')


------

# Ajouter un cercle inscrit dans le carré pour représenter le cercle unité
circle = plt.Circle((0, 0), 1, color='green', fill=False)
ax.add_artist(circle)


------

# Ajouter une légende pour les points
ax.legend(['Points dans le cercle','Points hors du cercle'])


------

# Afficher le graphique
plt.show()
</code></pre>
<p>2.6.3 Résultats et discussion
Pi est estimé à : 3.136
Pi est estimé à : 3.1424
Dans la Figure 2.3, la visualisation des points dans et hors de cercle pour différents nombres de points (N=1000 points, N=10000 points).
On peut voir dans la Figure 2.4 que les valeurs de Pi estimées en fonction du nombre de points.
Dans la Figure 2.5 une compilation des valeurs de π estimées par la méthode de Monte Carlo pour un nombre de points donné avec l'erreur relative et l'écart type.
A partir des résultats obtenus par la simulation, nous concluons :</p>
<ul>
<li>Lorsque N augmente, les valeurs de π estimées se rapprochent de plus en plus de la valeur exacte, mais le temps de calcul augmente également (voir Figure 2.4).</li>
<li>Chaque fois que nous effectuons un nouveau tirage pour la même valeur de N, nous obtenons une autre valeur différente estimée de π, en raison de la nature aléatoire des variables (voir Tableau 2.5).</li>
<li>Le caractère aléatoire de la méthode Monte Carlo nous pousse à répéter les tirages plusieurs fois pour estimer la valeur moyenne de π.
2.7 Conclusion
En conclusion, pour obtenir des résultats précis avec une incertitude acceptable, il est indispensable de simuler le transport d'un grand nombre de particules (au moins de l'ordre de 10^7). Cela implique des temps de calcul relativement longs, pouvant atteindre plusieurs jours (ref [9]).
...
3.1 Introduction
De nombreux logiciels de simulation par la méthode Monte Carlo ont été développés pour des applications dans des domaines tels que la physique médicale, la médecine nucléaire ou la dosimétrie interne. Certains de ces codes de calcul sont dans le domaine public et sont disponibles gratuitement. Les techniques de Monte Carlo sont idéales pour le transport des particules et sont considérées comme les plus efficaces pour estimer la distribution spatiale des particules et le dépôt d’énergie. Les codes Monte Carlo utilisés en médecine peuvent se classer en deux catégories: les codes généraux et les codes spécialisés.
3.2 Codes généraux
3.2.1 Penelope
Penelope simule le transport couplé électron-photon dans des systèmes matériels arbitraires constitués d'un certain nombre de régions homogènes limitées par des interfaces précises. Initialement, il est conçu pour simuler la pénétration et les effets de rayonnements ionisants.
Ce texte concerne les pertes d'énergie des positrons et des électrons dans la matière ainsi que les photons qui ont été introduits plus tard. Les modèles d'interaction adoptés (diffusion Rayleigh, diffusion Compton, effet photoélectrique et production de paires et annihilation des positons) sont simulés de manière détaillée, et les bases de données associées permettent de simuler le transport des électrons/positrons et des photons dans la gamme d'énergie allant de 50 eV à 1 GeV.
On présente aussi des codes de simulations par Monte Carlo, notamment EGS (Electron Gamma Shower) qui est un code de calcul Monte Carlo développé dès 1963 au SLAC par Nagel pour simuler des gerbes électromagnétiques de haute énergie (de quelques KeV à plusieurs TeV) dans des géométries arbitraires. Une nouvelle version EGS4, inclut un transport d’électrons de basse énergie (jusqu'à 1 KeV) amélioré, ainsi que la simulation de la diffusion Rayleigh. Une version plus récente d'EGS4 a été développée sous le nom de GSnre, qui propose une simulation plus précise des interactions des électrons et de positon.
On parle aussi du logiciel MCNP (Monte-Carlo Neutron Photon) développé par Breismeister qui suit les particules neutres (photons et neutrons), les électrons (positifs et négatifs) et dont la dernière version MCNPX, est étendue à certaines particules lourdes chargées. Ce code est directement lié à l'origine au Projet Manhattan. Initialement, ce code ne prenait en compte que le transport des particules non chargées comme les neutrons et les photons. Ce code dispose d’outils statistiques pour tester la convergence mathématique du résultat obtenu et des techniques de réduction de variance intégrées.
On aborde aussi le code PHITS et GEANT4. PHITS simule la réaction et le transport de plusieurs particules (une vingtaine de particules en plus d’ions lourds). GEANT4 est une plate-forme Monte Carlo pour la simulation du passage de particules à travers la matière.
Il existe également des codes spécifiques qui sont généralement dédiés à l'imagerie scintigraphique tels que SIMIND, développé par le professeur Michael Ljungberg à l'université de Lund en Suède qui décrit une caméra à scintillation standard adaptable pour réaliser plusieurs applications rencontrées dans l'imagerie SPECT. Et aussi SimSPECT qui est un code basé sur le code MCNP principalement pour le transport de photons.
En conclusion, la simulation du transport d’une particule dans la matière par Monte Carlo se déroule en plusieurs étapes jusqu’à ce que la particule soit absorbée, arrêtée par le milieu ou a quitté les limites de volume de simulation. Cette étape consiste à définir les dimensions et la forme des milieux d’interactions.Le texte corrigé est le suivant :
Déroulement de la simulation. On distingue trois paramètres qui définissent ces matériaux :</li>
<li>Les caractéristiques chimiques de ce milieu (la formule chimique, etc.).</li>
<li>Les dimensions du milieu :</li>
<li>$X_{min}$ et $X_{max}$ : sont les valeurs minimale et maximale de x, définissant la région de positions possibles de photons dans la géométrie selon l'axe OX.</li>
<li>$Y_{min}$ et $Y_{max}$ : sont la valeur minimale et maximale de y, définissant la région de positions possibles de photons dans la géométrie selon l'axe OY.</li>
<li>$Z_{min}$ et $Z_{max}$ : sont les valeurs minimale et maximale de z, définissant la région de positions possibles de photons dans la géométrie selon l'axe OZ.
Ces trois limites définissent le volume de simulation selon la forme géométrique désirée.</li>
</ul>
<h2 id="chapitre-4-simulation-de-transport-des-particules-par-monte-carlo"><a class="header" href="#chapitre-4-simulation-de-transport-des-particules-par-monte-carlo">Chapitre 4. Simulation de transport des particules par Monte Carlo</a></h2>
<h3 id="422-génération-des-particules"><a class="header" href="#422-génération-des-particules">4.2.2 Génération des particules</a></h3>
<hr />
<h1 id="afficher-le-graphique-1"><a class="header" href="#afficher-le-graphique-1">Afficher le graphique</a></h1>
<p>Toutes les informations associées à la particule sont définies dans le code S(x; Q; F), elles comprennent :</p>
<ul>
<li>La source S : génère les particules, elle peut être située à l'intérieur ou à l'extérieur du domaine où le dépôt de dose a lieu.</li>
<li>La position x : la position initiale ou position de départ des particules.</li>
<li>L’énergie E : l'énergie d’une particule de faisceau émis par la source.</li>
<li>Le cosinus directeur de la particule cos θ : c’est la direction initiale des photons par rapport à l'axe de faisceau.</li>
</ul>
<h3 id="423-tirage-aléatoire-de-la-position-p-avant-la-prochaine-interaction"><a class="header" href="#423-tirage-aléatoire-de-la-position-p-avant-la-prochaine-interaction">4.2.3 Tirage aléatoire de la position p avant la prochaine interaction</a></h3>
<p>La relation décrivant la loi de Beer-Lambert permet de donner la distance x parcourue par la particule avant la prochaine interaction sous forme T = %ln(f) (19)
Avec :</p>
<ul>
<li>φ : le nombre tiré aléatoirement entre 0 et 1, la variable aléatoire obéissant à une loi uniforme.</li>
<li>Σ = le coefficient d’atténuation total en cm^{-1}.</li>
<li>λ = 1/Σ : le libre parcours moyen en cm.
(...)
La position prochaine d’interaction est donnée par $X_{i+1} =X_i + S Q$ (20)
Avec :</li>
<li>$X_i$ : la position de la particule où la effectuée une interaction i.</li>
<li>$X_{i+1}$ : la position de la prochaine interaction i + 1.</li>
<li>$s = λln(φ)$ : la distance parcourue par une particule entre deux interactions successives.</li>
<li>Q : le vecteur directeur.
Son énergie est modifiée selon l’échantillonnage de l'interaction.
(...)</li>
</ul>
<h2 id="chapitre-4-simulation-de-transport-des-particules-par-monte-carlo-1"><a class="header" href="#chapitre-4-simulation-de-transport-des-particules-par-monte-carlo-1">Chapitre 4. Simulation de transport des particules par Monte Carlo</a></h2>
<h3 id="45-transport-des-protons-et-des-ions-de-carbone"><a class="header" href="#45-transport-des-protons-et-des-ions-de-carbone">4.5 Transport des protons et des ions de carbone</a></h3>
<p>Le transport de protons par Monte Carlo est modélisé en divisant le trajet d'un proton en une série de petites étapes, il est régi par trois processus principaux pouvoir d’arrêt, diffusion coulombienne et interactions nucléaires.</p>
<h3 id="451-pouvoir-darrêt"><a class="header" href="#451-pouvoir-darrêt">4.5.1 Pouvoir d’arrêt</a></h3>
<p>Les ions se transportent en perdant leur énergie par interaction avec des électrons atomiques. En Monte-Carlo, en négligeant l'interaction EM élastique et les interactions nucléaires avec le noyau atomique, la perte d’énergie pour chaque étape est calculée par les valeurs de pouvoir d’arrêt sous forme de tableaux (équation de Bethe Bloch).
$-\frac{dE}{dV} = \frac{4\pi n_m Z^2 e^4}{me^2 B^2 (4\pi\varepsilon_0)^2} \ln\left(\frac{2 m_e c^2 \beta^2}{I (1 - \beta^2)}\right)$
Avec :</p>
<ul>
<li>ρ = &quot;...&quot;Dans ce texte, nous avons les paramètres suivants :</li>
<li>p: Pas mentionné dans le texte</li>
<li>v : Vitesse de la particule</li>
<li>c : Vitesse de la lumière</li>
<li>E : Énergie de la particule</li>
<li>dx : Longueur du chemin</li>
<li>2z : Charge de la particule</li>
<li>e : Charge élémentaire</li>
<li>m : Masse au repos de l'électron</li>
<li>n : Densité numérique des électrons du matériau</li>
<li>[ : Potentiel d'excitation moyen du matériau
Figure 4.1 - Échantillonnage de trajet d'un ion
Chapitre 4 - Simulation de transport des particules par Monte Carlo
La perte d'énergie se dépose localement le long du trajet, sauf si le transfert d'énergie à un électron est supérieur à une valeur seuil.
Section 4.5.2 Diffusion
La dispersion des protons accompagne le ralentissement d'où la diminution de leur énergie cinétique qui est due principalement aux interactions avec les noyaux, sachant que la déviation de diffusion simples est assez faible pour appliquer des fonctions de densité de probabilité (les théories de diffusion multiple) qui permet d'accéder aux plusieurs événements de diffusion simple. Nous pouvons appliquer la technique d'échantillonnage pour calculer l'angle de diffusion à la fin de chaque étape.
Figure 4.2 - Diffusion d’un ion
Section 4.5.3 Interactions nucléaires
Les particules d'un faisceau ionique interagissent de manière nucléaire, élastiquement ou inélastiquement avant de s'arrêter. Elles génèrent des neutrons, d'autres particules et des isotopes à vie courte qui sont produits. La probabilité pour avoir ces interactions est déterminée par des données de section efficace mesurées ou des modèles nucléaires.
Chapitre 5 - Simulation par le code PHITS
Section 5.1 Introduction
PHITS (Particle and Heavy Ion Transport code System) est un des codes de simulation de transport de particules les plus réussis de Monte Carlo largement utilisé dans le monde entier. Il peut traiter le transport de presque toutes les particules, y compris les neutrons, les protons, les ions lourds, les photons et les électrons, sur une large gamme d'énergie en utilisant divers modèles de réactions nucléaires et bibliothèques de données. Il est écrit en Fortran et peut être exécuté sur les plates-formes Windows, Mac et Linux.
Dans ce chapitre, nous allons décrire le code PHITS, incluant l'architecture du fichier d'entrée, les modèles physiques utilisés pour déterminer la section efficace et le transfert d'énergie linéique.
Section 5.2 Description du fichier d’entrée «input»
Le fichier d’entrée est un texte au format libre. L’utilisateur n’a pas besoin d’écrire un programme en Fortran ni de compiler PHITS, ce qui rend le démarrage facile. Ce fichier a pour objectif de définir les paramètres, les variables et les formules nécessaires pour la simulation. Parmi ces éléments, on retrouve les caractéristiques de la particule à simuler (type, énergie, position et direction), ainsi que la géométrie de l'espace virtuel et les caractéristiques des matériaux.
Section 5.2.1 Structure du fichier input
Cette section indique la structure générale du fichier d'entrée de PHITS.
Section 5.2.2 Sections du fichier input
Chaque section du fichier &quot;input&quot; a une fonction spécifique, par exemple, la section &quot;[Title]&quot; comporte le titre de la simulation et la section &quot;[Parameters]&quot; contient les paramètres de simulation, tels que le mode de calcul et la géométrie, le nombre de particules à simuler, le nombre de faisceaux, ainsi que les énergies de coupure.
La section &quot;[source]&quot; donne les informations sur la production des particules par la source.</li>
</ul>
<hr />
<h1 id="afficher-le-graphique-2"><a class="header" href="#afficher-le-graphique-2">Afficher le graphique</a></h1>
<p>La géométrie est définie par trois sections : &quot;[Material]&quot;, &quot;[Surface]&quot; et &quot;[Cell]&quot;. En particulier, la section &quot;[Material]&quot; définit le nombre de matériaux, le nombre d’éléments chimiques et leur pourcentage ou abondance, par exemple H2O ou 12C.MAT [2] 12C
[Surface]
Cette section définit le nombre et la description des surfaces limitant une géométrie, telle que la sphère (notée $SO$), le cylindre, le cube, etc. Par exemple :
— 1 PX 2 # plan perpendiculaire à l'axe OX en z = 2
— 2 SO 5 # sphère centrée, de rayon 5cm
CHAPITRE 5. SIMULATION PAR LE CODE PHITS
Surface Symbol Type Explanation Equation Parameters
P   plane   multi-purpose   $Ax+By+Cz-D=0$    A, B, C, D
PX   vertical with X-axis   $x-D=0$   D
PY   vertical with Y-axis   $y-D=0$   D
PZ   vertical with Z-axis   $z-D=0$   D
SO   sphere, origin is center   $x^2+y^2+z^2-R^2=0$   R
Et d'autres détails sur les coordonnées et les équations des différentes géométries en 3 dimensions sont citées dans la FIGURE 5.2.
[Cell]
Dans cette section, les cellules peuvent être définies en fonction des surfaces décrites dans la section [Surface] et des matériaux décrits dans la section [Material]. Les cellules doivent être définies comme des espaces fermés, et des espaces virtuels pour les calculs de transport de particules peuvent être générés en combinant des cellules définies. Dans PHITS, les &quot;vides externes&quot; doivent être explicitement définis comme des éléments.
Cette section est définie par :
— Le numéro de cellule : n'importe quel numéro de 1 à 999,999 peut être utilisé.
— Densité du matériau : lorsque la valeur donnée est positive, il s'agit d'une densité de particules $[atomes/cm^3]$, et est négative s'il s'agit d'une densité de masse $[g/cm^3]$ [40].
— Le numéro de la surface donné dans la section [Surface].
Exemple :
— 100 1 -1.01 -2
Cette cellule est nommée 100, remplie par le matériau 1 défini dans la section [Material] (ici H2O) de densité 1.01 g/cm³ et prenant la forme de la surface indiquée dans la section [Surface] (ici une sphère).
Les Tallies
Ce &quot;tally&quot; comporte deux catégories qui sont implémentées dans le code PHITS. L'une concerne la géométrie et l'autre consiste à calculer les quantités physiques.
[T-Track]
Ce &quot;tally&quot; peut être utilisé pour obtenir la fluence dans n'importe quelle région spécifiée. Chaque fois que des particules traversent cette région, la longueur de la trajectoire est évaluée. En divisant ces longueurs par le volume de la région et le nombre de particules sources, on obtient la fluence de particules en unités de $[cm/source]$ [41].
[T-Deposit]
Ce &quot;tally&quot; peut être utilisé pour obtenir les énergies déposées (chaleur) dans certaines régions.
[T-LET]
Ce &quot;tally&quot; peut être utilisé pour obtenir des informations sur la longueur de la trajectoire et la dose en fonction du TLE ($dE/dz$) d'un matériau donné, en tenant compte des pertes d’énergie des particules chargées et des noyaux [41].
[T-Volume]
PHITS a une fonction de calcul automatique pour obtenir le volume de chaque cellule à l'aide de $[T-Volume]$, en effectuant une intégration de Monte Carlo [41].
[T-3Dshow]
Ce &quot;tally&quot; produit une sortie de géométrie graphique en vue 3D. Ce &quot;tally&quot; peut être généré sans calcul de transport en utilisant l'option $icntl=11$ dans la section [Paramètres].
T-Rshow]
Cette section produit une sortie de géométrie graphique pour les régions délimitées par un maillage XYZ avec un tracé de couleur proportionnel aux quantités physiques des régions. Ces sorties peuvent être obtenues sans calcul de transport en utilisant 'option $icnt1=9$ dans la section [Paramètres] [41].
[END]
Indique la fin de la simulation.
5.3 Les modèles physiques dans PHITS
PHITS a également divisé la réaction en un modèle de voie d'entrée et un modèle de voie de sortie pour mettre en œuvre divers modèles physiques permettant le transport de nombreux types de particules (y compris les photons, les électrons, les neutrons, les protons, les particules et les ions lourds) sur une large gamme d'énergie allant de 0,1 meV à 1 TeV.
5.3.1 JAM et INCL4.6
Il s'agit d'un modèle de cascade hadronique pour simuler le stade dynamique des réactions nucléaires induites par les hadrons dont l'énergie va de 20 MeV jusqu’à 3 GeV, explicitant ainsi leurs antiparticules [39],[40], [42],[43].
5.3.2 Le modèle JQMD
La version 2 améliorée de ce modèle (JAERI Quantum Molecular Dynamics) permet une reproduction plus précise des sections efficaces de fragmentation pour simuler la phase dynamique des réactions induites par des ions lourds d'énergie inférieure à 3,5GeV/nucléon [Niita-95],[Chiba-96-a], [Chiba-96-b| et [Ogawa-15| [39],[40], [42],[43].
5.3.3  Le modèle SMM (Statistical Multi-fragmentation Model)
Ce modèle consiste à simuler les réactions de fragmentation des collisions noyau-noyau.
L'énergie relativiste et le proton-noyau sont pris en compte lorsqu'excitation de ces noyaux est suffisamment élevée (Excitation &gt; 2,5 MeV /nucléon) [Ogawa-13][39],[40], [42],[43].
Le modèle GEM (Generalized Evaporation Model) est utilisé par le code PHITS pour simuler l'évaporation statistique des particules légères (Z&lt;12) et la fission des noyaux lourds (A&gt;70) [Furihata-01]. Cela permet d'estimer de manière précise les spectres de rayonnements et les taux de production d'isomères.
La librairie de données nucléaires JENDL-4.0 est utilisée pour le calcul du transport des neutrons de moins de 20 MeV et des émissions des particules secondaires induites par ces neutrons [39],[40],[42],[43].
Le modèle INCL 4.6 (Intra-nuclear cascade of Liege) est utilisé pour simuler le transport des neutrons plus énergétiques [Boudard-13].</p>
<hr />
<h1 id="afficher-le-graphique-3"><a class="header" href="#afficher-le-graphique-3">Afficher le graphique</a></h1>
<p>L'algorithme EGS5 a été introduit pour simuler les interactions atomiques des électrons, des positrons et des photons sur une large gamme d'énergies allant de 1 keV à 1 TeV. Cette mise en place améliore la précision de la simulation du transport d'électrons, en particulier pour les énergies plus faibles, ce qui est très important du point de vue des applications de physique médicale [29].
Dans le cadre de cette étude, nous avons utilisé le code PHITS pour simuler le transport des particules utilisées en hadronthérapie (proton, 12C, neutron...) en déterminant les caractéristiques balistiques des protons et des ions de carbone 12 et en suivant les particules secondaires qui contribuent à la déposition de dose.
La première étape de cette simulation consiste à créer un fantôme de géométrie simple, un parallélépipède de dimensions 20 cm x 20 cm x 40 cm. Nous avons ensuite créé une source de faisceau cylindrique de protons de diamètre 8 cm, d'énergie E_y = 140 MeV. Le faisceau est dirigé le long de l'axe z. Le matériau utilisé dans cette simulation est de l'eau, avec une densité de p=1g/cm³. Le matériau polyéthylène, C2H4, est aussi inclus dans la simulation pour validation du code utilisé.
Les résultats de la simulation sont presque en accord avec l'expérience, avec une faible différence notable au niveau du pic et concernant sa position et sa hauteur. Cela peut s'expliquer par plusieurs paramètres comme le pas de simulation, qui lorsqu'il est plus petit, le nombre de collisions est important et la dose déposée est donc plus importante. En conclusion, cette faible différence est acceptable en raison des incertitudes associées aux mesures expérimentales et aux modèles physiques utilisés dans le code PHITS.L'avantage des protons est plus important que celui des rayons X et des électrons. On en déduit que la dose déposée est principalement due aux protons parmi les particules incidents et presque toute l'énergie incidente est déposée au pic de Bragg, ce qui est une caractéristique fondamentale des protons.
La figure 6.3.b montre l'apparition des fluctuations. Ces fluctuations deviennent importantes lorsque le nombre de particules est faible. Ceci est du d'une part au caractère stochastique et aléatoire du code PHITS basé sur la méthode Monte Carlo et d'autre part à la répartition non uniforme en profondeur.
La figure 6.4 montre la carte de la distribution de dose autour du faisceau incident dans le plan xz, où la barre de couleur représente la dose absorbée par le milieu dont la valeur maximale correspond à la couleur rouge et la minimale à la couleur bleue.
La figure 6.5 montre les régions où les traces occupées par les particules primaires et secondaires autour du faisceau primaire sont les plus nombreuses, signalées par la couleur rouge pour le nombre élevé de particules et bleue pour le nombre faible.
Le dépôt d’énergie obtenu peut s’effectuer de différentes manières: par collision des protons incidents avec les électrons du milieu cible (l'eau), par collision des protons avec les noyaux et finalement la particule peut perdre son énergie par freinage causé par le champ électrique créé par les noyaux.
Ces collisions produisent des particules secondaires, y compris le neutron, photon,deutrino, tritium,et les électrons. Ces particules secondaires contribuent à une faible dose d'environ 0,01% de la dose totale déposée avant et au pic de Bragg. Cette contribution est principalement due à l'isotope ²H. Par contre, après le pic de Bragg, la dose est déposée uniquement par les particules neutrons et photons dont la trajectoire dépasse 20 cm dans l'eau.
La figure 6.8 montre que le fait d’augmenter l'énergie des particules primaires entraîne une augmentation de la profondeur de pénétration des protons dans l'eau, cependant, la hauteur du pic de Bragg diminue. Quand le parcours de la particule est grand (l’énergie incidente est grande), le nombre de collisions effectuées, notamment inélastiques, est important et s’accompagne par la diminution d’énergie.Jusqu'à une énergie faible qui sera intégralement déposée sous forme de pic, différentes énergies de 50 MeV, 95 MeV, 140 MeV et 200 MeV correspondent à des positions du pic de Bragg de 2,1, 6,9, 13,8 et 25,8 respectivement, avec les largeurs à mi-hauteur (en cm) comme suit : 0,2, 0,3, 0,4 et 0,6 (Voir le tableau 6.1 — Largeur &amp; mi hauteur pour différentes énergies de protons). Du tableau 6.1, on constate que lorsque la profondeur dans l'eau augmente, la largeur à mi-hauteur elle aussi augmente. Cela traduit une dispersion du faisceau de protons ainsi qu'une perte de la précision du dépôt de dose avec la profondeur.
Nous abordons ensuite la simulation de transport d'ions Carbone 12 grâce au matériau et à la géométrie utilisée précédemment, remplacés par une source d'ions de Carbone 12 de 264 MeV. La dose absorbée en profondeur par le fantôme est calculée dans la section tally, précisément par [T-Deposit].
La courbe de la figure 6.9 générée par le logiciel PHITS montre que les ions de carbone primaires sont principalement responsables de la dose déposée à hauteur d'environ 93% dans le fantôme avant et au pic de Bragg. Cependant, les particules secondaires ne contribuent qu'à 7% de la dose totale déposée.
Au pic de Bragg pour z=13.8 cm, tous les ions de Carbone 12 du faisceau primaires sont arrêtés par le milieu. Ceci marque la fin de leur parcours.
Le tableau 6.2 donne le parcours et le taux de contribution en dose des particules secondaires. Nous comparons ensuite des caractéristiques d'un ion carbone d'une énergie de 270MeV/u avec un ion léger comme le proton et un ion lourd comme le néon.</p>
<hr />
<h1 id="afficher-le-graphique-4"><a class="header" href="#afficher-le-graphique-4">Afficher le graphique</a></h1>
<p>Le tableau 6.3 résume les résultats en donnant la largeur à mi-hauteur et le taux de dispersion en profondeur des deux ions. A partir de ce tableau, on peut déduire que le faisceau de protons dispose d'une précision de dépôt de dose inférieure à celle des ions carbone et que les ions carbone disposent d'une dispersion en profondeur inférieure à celle des protons.
Enfin, une simulation par le logiciel PHITS d'une part d'un faisceau d'ions carbone et d'autre part d'un faisceau d'ions néon permet d'obtenir les courbes de la figure 6.12.
Figure 6.12 montre la distribution de dose en profondeur d’ions carbone d'énergie E=400 MeV/u et de ions de néon E=560 MeV. Nous constatons que la dose déposée avant le pic de Bragg par les ions carbone est presque constante et faible par rapport aux ions de néon. Après le pic, la queue de fragmentation des ions néons est plus importante que celle des ions carbone cependant la dispersion en profondeur est la même pour les deux types d'ions.
Dans le tableau 6.3, nous calculons le taux de dose par rapport à celle déposée au pic de Bragg à l'entrée z=0 du fantôme et juste après le pic à z=27,6 cm.
| Ions  | Taux de dose pour z =0 cm  | Taux de dose pour z = 27,6 cm |
|-------|---------------------------|-------------------------------|
| Nt    | 0,35                      | 0,18                          |
| Lot   | 0,23                      | 0,091                         |
Tableau 6.4 - Taux de dose par rapport au pic de Bragg pour les ions de carbone et ions de néon.
La fragmentation est un phénomène de décomposition d’un noyau en noyaux légers et d'autres particules.
Chapitre 6 - Résultats et Discussions
Conclusion : Un dépôt d'énergie modéré et presque constant à l'entrée et maximal en fin de parcours par les ions de carbone 12 et de protons, une faible dispersion en profondeur et latéralement, permet d'irradier précisément le volume ciblé pour détruire les tumeurs tout en protégeant les organes sains en entrée. Ces caractéristiques mettent en évidence l'intérêt balistique des ions pour un traitement par rapport aux électrons et aux rayons X. Le traitement avec les ions carbone est plus efficace que celui des protons.
Dans ce travail, nous avons d'abord présenté un aperçu du principe d'interaction des particules avec la matière nécessaire pour comprendre le transport et le transfert d'énergie d'une particule dans un milieu biologique. Nous avons utilisé la méthode de Monte-Carlo qui repose sur l’échantillonnage aléatoire. Nous avons validé notre code avec les mesures dans le polyéthylène fournies par la NASA puis réalisé une simulation d'un faisceau de protons et d'ions carbone 12 monoénergétiques dans l'eau. Nos résultats confirment que le dépôt d’énergie dans l’eau par un faisceau de protons et celui d’ions carbone présente une caractéristique commune en fin de leur parcours, pic de Bragg.
Conclusions Générales : La recherche accompagne la mesure de section efficace de fragmentation pour améliorer les modèles nucléaires utilisés dans le système de planification. Nous avons rencontré des problèmes techniques notamment liés à la nécessité d'un grand nombre de particules pour avoir une estimation précise par Monte Carlo et la difficulté de se familiariser avec un code de simulation. Néanmoins, ce travail initie une perspective pour améliorer notre connaissance sur le comportement des ions dans un milieu biologique, étudier les fragments produits et leurs propriétés, et améliorer les moyens de radioprotection contre les particules secondaires.</p>
<h1 id="résumé"><a class="header" href="#résumé">Résumé</a></h1>
<p>Les méthodes de simulation par Monte Carlo simulent la réalité pour résoudre des problèmes complexes grâce à des algorithmes basés sur l'échantillonnage de nombres aléatoires générés par un générateur spécifique. Dans ce mémoire, ces méthodes sont utilisées pour examiner le transport des ions dans l'eau en utilisant le code PHITS, pour en déduire leurs caractéristiques balistiques.</p>
<p>L'efficacité des ions de carbone à la fin de leur trajet, leur distribution de dose profonde caractérisée par le pic de Bragg et leur faible pénombre latérale, relativement aux photons et aux électrons, les rendent privilégiés en thérapie tumorale, en particulier pour les tumeurs radio-résistantes près des organes à risque.</p>
<h1 id="introduction"><a class="header" href="#introduction">Introduction</a></h1>
<p>Simuler des phénomènes réels à travers une modélisation précise permet à la réalité physique de s'incarner par des solutions informatiques. Les techniques de simulation de Monte Carlo, techniques probabilistes qui calculent des valeurs numériques approximatives, ont été mises en place pour répondre aux besoins de projets d'envergure, comme le projet Manhattan pendant la Seconde Guerre mondiale.</p>
<p>Il existe des problèmes mathématiques et physiques qui ne peuvent être résolus par des méthodes analytiques, tels que la résolution de l'équation de Boltzmann; les méthodes de Monte Carlo sont donc les outils préconisés pour les résoudre. Elles sont fréquemment utilisées en physique, chimie, biologie, statistiques et dans bien d'autres domaines.</p>
<p>Dans le domaine de la physique médicale, leurs applications sont multiples: en médecine nucléaire, en hadronthérapie, en radiothérapie, en curiethérapie, etc.</p>
<h1 id="organisation-du-mémoire"><a class="header" href="#organisation-du-mémoire">Organisation du Mémoire</a></h1>
<p>Ce mémoire est divisé en six chapitres.</p>
<ol>
<li>
<p><strong>Notions Physiques en Oncologie</strong> : Ce chapitre traite des nombreux aspects de l'interaction des particules avec la matière, en mettant l'accent sur la radiothérapie, l'hadronthérapie et
l'utilisation d'électrons, de photons et d'ions en traitement contre le cancer.</p>
</li>
<li>
<p><strong>Généralités de la méthode Monte Carlo</strong></p>
</li>
<li>
<p><strong>Différents codes Monte Carlo pour la simulation des particules</strong></p>
</li>
<li>
<p><strong>Etude du transport et du transfert d'énergie par les éléctrons, les photons et les ions</strong></p>
</li>
<li>
<p><strong>Présentation du code de simulation PHITS</strong></p>
</li>
<li>
<p><strong>Résultats et Discussion</strong></p>
</li>
</ol>
<h2 id="chapitre-1-notions-physiques-en-oncologie"><a class="header" href="#chapitre-1-notions-physiques-en-oncologie">Chapitre 1: Notions Physiques en Oncologie</a></h2>
<p>La radiothérapie est une méthode médicale qui utilise les radiations ionisantes pour détruire les cellules cancéreuses, tout en préservant les tissus sains. En fonction du type, de l'emplacement et de l'étage de la tumeur, ainsi que de l'état de santé général du patient, elle peut être mise en oeuvre conjointement avec d'autres traitements, tels que la chimiothérapie ou la chirurgie.</p>
<h3 id="12-la-radiothérapie-1"><a class="header" href="#12-la-radiothérapie-1">1.2 La Radiothérapie</a></h3>
<h4 id="121-radiothérapie-externe-1"><a class="header" href="#121-radiothérapie-externe-1">1.2.1 Radiothérapie Externe</a></h4>
<p>La radiothérapie externe est une technique anticancéreuse communément utilisée qui utilise des rayons ionisants, à savoir les photons et les électrons, provenant d'une source externe au patient. Selon la tumeur à traiter, cette méthode peut être curative ou palliative.</p>
<h4 id="122-radiothérapie-interne-1"><a class="header" href="#122-radiothérapie-interne-1">1.2.2 Radiothérapie Interne</a></h4>
<p>La radiothérapie interne implique une mise en contact directe de sources radioactives avec la tumeur, afin de limiter l'irradiation des tissus sains.</p>
<h4 id="123-transfert-dénergie-par-les-photons"><a class="header" href="#123-transfert-dénergie-par-les-photons">1.2.3 Transfert d’énergie par les photons</a></h4>
<p>La radiothérapie externe utilise des rayons X de très haute énergie, entre 4 et 25 MeV. À ces niveaux d'énergie, 4 types d'interactions peuvent se produire entre les photons et la matière.</p>
<h4 id="124-transfert-dénergie-par-les-électrons"><a class="header" href="#124-transfert-dénergie-par-les-électrons">1.2.4 Transfert d’énergie par les électrons</a></h4>
<p>Dans le processus de transfert d'énergie, les électrons en mouvement interagissent avec les électrons des atomes du milieu. Parmi les principales interactions des électrons avec les atomes, on retrouve :</p>
<ul>
<li>La diffusion élastique: une simple déviation de l’électron incident.</li>
</ul>
<h1 id="résumé-1"><a class="header" href="#résumé-1">Résumé</a></h1>
<p>Dans ce texte, nous abordons différents aspects de la physique des particules, y compris la diffusion inélastique, le rayonnement de freinage, la hadronthérapie, le transfert d'énergie linéique, la dose déposée, ainsi que la méthode de Monte Carlo.</p>
<h2 id="diffusion-inélastique-et-rayonnement-de-freinage"><a class="header" href="#diffusion-inélastique-et-rayonnement-de-freinage">Diffusion Inélastique et Rayonnement de Freinage</a></h2>
<p>La diffusion inélastique provoque l'éjection d'un électron de l'atome, tandis que le rayonnement de freinage voit l'électron freiné et dévié à proximité d'un noyau atomique. L'énergie perdue par l'électron est transportée par un photon, qui peut interagir avec la matière plus loin.</p>
<p>L'un des aspects particuliers de ces phénomènes est que la trajectoire d'un électron est, en moyenne, proportionnelle à son énergie initiale et inversement proportionnelle à la densité électronique du matériau.</p>
<h2 id="hadronthérapie"><a class="header" href="#hadronthérapie">Hadronthérapie</a></h2>
<p>La hadronthérapie est une technique anticancéreuse qui utilise un faisceau de hadrons - notamment des protons et des ions de carbone - pour détruire les cellules cancéreuses résistantes à la radio. Les hadrons, qui signifient &quot;forces&quot; en grec, sont constitués de quarks et sont utilisés pour les protons et les neutrons en thérapie tumorale.</p>
<h2 id="interaction-des-ions-dans-la-matière"><a class="header" href="#interaction-des-ions-dans-la-matière">Interaction des Ions dans la Matière</a></h2>
<p>Les ions, protons et ions de carbone interagissent avec la matière par divers types de collisions : élastiques, inélastiques et nucléaires inélastiques. Quand l'énergie du projectile est suffisamment elevée pour franchir la barrière coulombienne, les réactions noyau-noyau dominent et peuvent entraîner la fragmentation des ions et des cibles.</p>
<h2 id="transfert-dÉnergie-linéique"><a class="header" href="#transfert-dÉnergie-linéique">Transfert d’Énergie Linéique</a></h2>
<p>Le transfert d'énergie linéique (TEL), exprimé en keV/$\mu$m, est l'énergie moyenne transmise au milieu par la particule par unité de longueur.</p>
<h2 id="dose-déposée"><a class="header" href="#dose-déposée">Dose Déposée</a></h2>
<p>La dose déposée ou absorbée par les tissus, exprimée en grays (J/kg), est l'énergie moyenne déposée par les particules ionisantes dans un volume de masse 'dm'.</p>
<h2 id="dose-biologique"><a class="header" href="#dose-biologique">Dose Biologique</a></h2>
<p>La dose biologique ou dose équivalente photons, exprimée en gray équivalent cobalt (60Co), est fonction de l'efficacité biologique relative.</p>
<h2 id="simulation-de-monte-carlo"><a class="header" href="#simulation-de-monte-carlo">Simulation de Monte Carlo</a></h2>
<p>La simulation de Monte Carlo utilise un générateur de nombres aléatoires pour échantillonner la distribution de probabilités décrivant un processus physique.</p>
<p>Votre demande a été comprise. Mon rôle maintenant est d'optimiser le texte, de clarifier les concepts, d'éliminer les redondances, et de mettre en œuvre un formatage Markdown et LaTeX et en gardant les mêmes tableaux.</p>
<h1 id="instructions"><a class="header" href="#instructions">Instructions</a></h1>
<p>Voici les étapes que nous allons suivre :</p>
<ol>
<li><strong>Suppression des phrases introductives</strong> : Nous rendrons le message plus concis en supprimant les phrases superflues.</li>
<li><strong>Élimination des redondances</strong> : Le texte sera réorganisé pour supprimer les répétitions.</li>
<li><strong>Clarification</strong> : Nous expliquerons simplement les concepts complexes et donnerons des exemples pertinents.</li>
<li><strong>Structuration</strong> : Pour faciliter la compréhension, nous décomposerons les idées en sous-sections.</li>
<li><strong>Langage</strong> : Nous userons d'un langage simple et adapté à un public instruit non spécialisé.</li>
</ol>
<h1 id="texte-optimisé"><a class="header" href="#texte-optimisé">Texte optimisé</a></h1>
<p>Nous discuterons ici de trois modèles statistiques majeurs : la distribution continue uniforme, la méthode d'échantillonnage de Von Neumann et l'approximation par Monte Carlo.</p>
<h2 id="distribution-continue-uniforme"><a class="header" href="#distribution-continue-uniforme">Distribution continue uniforme</a></h2>
<p>Si R est uniformément distribué sur l'intervalle [0, 1], alors la variable $z = -\ln{(1 - R)}$ suit la distribution $p(x)$. La probabilité que la variable x soit plus grande que d représente la chance que le rayonnement gamma ne réagit pas au matériau. Cette probabilité peut être définie par l'expression $exp(-pd) = 1 - F(d)$, ce qui mesure l'inefficacité de la simulation pour certaines tâches.</p>
<h2 id="méthode-déchantillonnage-de-von-neumann"><a class="header" href="#méthode-déchantillonnage-de-von-neumann">Méthode d'échantillonnage de Von Neumann</a></h2>
<p>Von Neumann a proposé une méthode d'échantillonnage alternative : tirer aléatoirement une variable uniforme R dans l'intervalle [0, 1] et tester si elle doit être acceptée ou rejetée. En utilisant cette méthode avec deux fonctions de densité de probabilités $f_1(x)$ et $f(x)$, définies par la relation $p(x) = f_1(x) - f(x)$, nous sélectionnons x en utilisant $f_1(x)$, puis appliquons la méthode de rejet pour $f(x)$.</p>
<h2 id="approximation-par-monte-carlo"><a class="header" href="#approximation-par-monte-carlo">Approximation par Monte Carlo</a></h2>
<p>Les résultats des calculs par Monte Carlo sont soumis à des incertitudes statistiques. Pour réduire les fluctuations, nous devons généralement simuler un grand nombre de particules (de centaines à des milliards). Plus le nombre de recours générés est important, plus l'incertitude associée au volume d'intérêt est faible, ce qui rend les résultats estimés par Monte Carlo plus précis.</p>
<h1 id="approximation-de-π"><a class="header" href="#approximation-de-π">Approximation de π</a></h1>
<p>L'exemple du calcul de π à travers le modèle de Monte Carlo est présenté ici. Ce processus estime π par approximation de la surface d'un quart de cercle de rayon 1.</p>
<pre><code class="language-python">compte_dedans = nombre de points à l’intérieur du cercle D.
</code></pre>
<p>Pour obtenir une approximation de π, on utilise l'expression :</p>
<pre><code class="language-python">π = 4 * compte_dedans / nombre_points
</code></pre>
<h2 id="code-de-simulation"><a class="header" href="#code-de-simulation">Code de simulation</a></h2>
<p>Voici un exemple de code pour réaliser cette simulation.</p>
<pre><code class="language-python">import random
import matplotlib.pyplot as plt
</code></pre>
<h2 id="instructions-pour-le-texte"><a class="header" href="#instructions-pour-le-texte">Instructions pour le Texte</a></h2>
<p>Il faut s'assurer de respecter les directives suivantes lors de l'écriture et la structuration du texte :</p>
<ol>
<li><strong>Minimiser les phrases d'introduction</strong> : Rendez le message plus direct en éliminant les phrases inutiles et en présentant les informations de manière concise.</li>
<li><strong>Éviter les redondances</strong> : Évitez de répéter les mêmes informations en reformulant ou en réorganisant le texte.</li>
<li><strong>Clarifier</strong> : Expliquez les idées ou termes complexes de façon simple. Fournissez des exemples pertinents. Pour les termes spécifiques à un domaine particulier, fournissez une brève explication.</li>
<li><strong>Structuration</strong> : Divisez les idées en sous-sections pour faciliter la compréhension. Utilisez des mots de liaison pour assurer une transition en douceur entre les sections.</li>
<li><strong>Langage approprié</strong> : Utilisez un langage simple et compréhensible. Évitez le jargon complexe. Veillez à ce que le texte convienne à un public cultivé, mais non spécialiste.</li>
</ol>
<h2 id="texte-original"><a class="header" href="#texte-original">Texte Original</a></h2>
<pre><code class="language-markdown"># Nombre de points à utiliser pour l’estimation
nombre_points = 10000
</code></pre>
<p>Cette portion de code définit simplement le nombre de points à utiliser pour une estimation. Ce nombre est défini à 10,000 points.
Selon les directives suivantes :</p>
<ul>
<li><strong>Élimination des introductives</strong></li>
<li><strong>Évitez la redondance</strong></li>
<li><strong>Présentation claire</strong></li>
<li><strong>Structure</strong></li>
<li><strong>Langage</strong></li>
</ul>
<p>Le texte fourni existe en version modifiée :</p>
<hr />
<h3 id="comptage-des-points-dans-le-cercle"><a class="header" href="#comptage-des-points-dans-le-cercle">Comptage des Points dans le Cercle</a></h3>
<p>Pour effectuer un comptage de points dans un cercle, vous pouvez initialiser un compteur à zéro comme montré dans le code suivant :</p>
<pre><code class="language-python">compte_dedans = 0
</code></pre>
<p>Ce morceau de code crée une variable <code>compte_dedans</code> et lui attribue la valeur 0. Ce compteur sera ensuite utilisé pour suivre le nombre de points qui tombent à l'intérieur du cercle.
Voici une reformulation structurée du texte en utilisant le formatage Markdown.</p>
<hr />
<h3 id="suppression-des-phrases-introductives"><a class="header" href="#suppression-des-phrases-introductives">Suppression des Phrases Introductives</a></h3>
<p>Le texte original introduisait les concepts et présentait les directives de manière plutôt indirecte. En supprimant ces phrases d'introduction, le message est plus direct et les informations sont présentées de manière plus concise.</p>
<h3 id="Élimination-de-la-redondance"><a class="header" href="#Élimination-de-la-redondance">Élimination de la Redondance</a></h3>
<p>La redondance du texte original a été éliminée en reformulant et en réorganisant le texte pour éviter les répétitions inutiles.</p>
<h3 id="simplification-et-explication-de-concepts"><a class="header" href="#simplification-et-explication-de-concepts">Simplification et Explication de Concepts</a></h3>
<p>Les termes spécifiques et les idées complexes du texte original ont été simplement expliqués et des exemples pertinents ont été donnés pour clarifier le contenu.</p>
<h3 id="structuration-du-texte"><a class="header" href="#structuration-du-texte">Structuration du Texte</a></h3>
<p>Le texte a été décomposé en sous-sections pour faciliter la compréhension du lecteur. Des mots de liaison ont été utilisés pour assurer une transition fluide entre les sections.</p>
<h3 id="utilisation-dun-langage-simple-et-approprié"><a class="header" href="#utilisation-dun-langage-simple-et-approprié">Utilisation d'un Langage Simple et Approprié</a></h3>
<p>Le langage du texte original a été adapté pour convenir à un public éduqué, mais non spécialisé. Le jargon inutile a été évité.</p>
<hr />
<h3 id="texte-reformulé"><a class="header" href="#texte-reformulé">Texte Reformulé</a></h3>
<p>&quot;</p>
<h2 id="stockage-des-coordonnées-des-points"><a class="header" href="#stockage-des-coordonnées-des-points">Stockage des Coordonnées des Points</a></h2>
<p>Dans cette section du code, nous utilisons des listes pour stocker les coordonnées des points qui se trouvent à la fois à l'intérieur et à l'extérieur du cercle.</p>
<pre><code class="language-python">x_dans = []
y_dans = []
x_dehors = []
y_dehors = []
</code></pre>
<p>Ces listes vides (<code>x_dans</code>, <code>y_dans</code>, <code>x_dehors</code>, <code>y_dehors</code>) seront remplies avec les coordonnées x et y des points à mesure qu'ils sont identifiés comme étant à l'intérieur ou à l'extérieur du cercle.</p>
<p>&quot;</p>
<h2 id="guide-de-restructuration-du-texte"><a class="header" href="#guide-de-restructuration-du-texte">Guide de restructuration du texte</a></h2>
<h3 id="suppression-de-lintroduction"><a class="header" href="#suppression-de-lintroduction">Suppression de l'introduction</a></h3>
<p>Le texte est modifié pour supprimer les phrases introductives et rendre le message plus direct et concis.</p>
<h3 id="Éviter-la-redondance"><a class="header" href="#Éviter-la-redondance">Éviter la redondance</a></h3>
<p>Les informations répétées sont reformulées ou réorganisées pour éviter la redondance.</p>
<h3 id="clarté-de-la-présentation"><a class="header" href="#clarté-de-la-présentation">Clarté de la présentation</a></h3>
<p>Les termes ou idées complexes sont expliqués de manière simple, avec des exemples pertinents si nécessaire. Si des termes sont spécifiques à un domaine, ils sont brièvement expliqués.</p>
<h3 id="structure-du-texte"><a class="header" href="#structure-du-texte">Structure du texte</a></h3>
<p>Les idées sont décomposées en sous-sections pour faciliter la compréhension. Des mots de liaison sont utilisés pour assurer une transition fluide entre les sections.</p>
<h3 id="langage-utilisé"><a class="header" href="#langage-utilisé">Langage utilisé</a></h3>
<p>Un langage simple et approprié est utilisé pour le texte. Le jargon inutile est évité, de manière à adapter le texte à un public instruit, mais non spécialisé.</p>
<h2 id="texte-transformé"><a class="header" href="#texte-transformé">Texte Transformé</a></h2>
<p>'''</p>
<h2 id="génération-de-points-aléatoires"><a class="header" href="#génération-de-points-aléatoires">Génération de Points Aléatoires</a></h2>
<p>La boucle ci-dessous est utilisée pour générer des points aléatoires.</p>
<pre><code class="language-python">for i in range(nombre_points):
</code></pre>
<h2>Note : Dans ce code, <code>nombre_points</code> représente le nombre de points aléatoires que vous souhaitez générer. Par chaque itération, le code génère un nouveau point aléatoire.
'''</h2>
<p><strong>Génération de Coordonnées Aléatoires</strong></p>
<p>Pour générer des coordonnées aléatoires en Python, utilisez les fonctions <code>random.uniform(a, b)</code> de la bibliothèque <code>random</code>. Ces fonctions renvoient un nombre à virgule flottante aléatoire <code>N</code> tel que <code>a &lt;= N &lt;= b</code> pour <code>a &lt;= b</code> et <code>b &lt;= N &lt;= a</code> pour <code>b &lt; a</code>.</p>
<p>Par exemple, pour générer des coordonnées <code>x</code> et <code>y</code> aléatoires dans l'intervalle <code>[-1, 1]</code> :</p>
<pre><code class="language-python">x = random.uniform(-1, 1)
y = random.uniform(-1, 1)
</code></pre>
<p>Dans ce code, <code>x</code> et <code>y</code> deviennent des nombres aléatoires dans l'intervalle <code>[-1, 1]</code>.</p>
<h1 id="calcul-de-la-distance-par-rapport-à-lorigine-00"><a class="header" href="#calcul-de-la-distance-par-rapport-à-lorigine-00">Calcul de la Distance par rapport à l'Origine (0,0)</a></h1>
<p>Pour calculer la distance entre un point donné <code>(x, y)</code> et l'origine <code>(0,0)</code> dans un système de coordonnées bidimensionnel, nous utilisons la formule :</p>
<pre><code class="language-python">distance = (x**2 + y**2)**0.5
</code></pre>
<p>Cette formule est basée sur le théorème de Pythagore dans la géométrie euclidienne.</p>
<h2 id="détails-de-la-formule"><a class="header" href="#détails-de-la-formule">Détails de la Formule</a></h2>
<p>Dans cette formule :</p>
<ul>
<li><code>x</code> et <code>y</code> sont les coordonnées du point.</li>
<li><code>**2</code> signifie &quot;élevé à la puissance de 2&quot;, ce qui revient à multiplier une quantité par elle-même.</li>
<li><code>**0.5</code> signifie &quot;élevé à la puissance de 0.5&quot;, connu également comme la racine carrée.</li>
</ul>
<p>Résultat, <code>distance</code> est la distance euclidienne entre l'origine et le point <code>(x, y)</code>.</p>
<h2 id="exemple-dutilisation"><a class="header" href="#exemple-dutilisation">Exemple d'utilisation</a></h2>
<p>Supposons que nous ayons un point à la position <code>(3,4)</code>. En insérant ces valeurs dans la formule, nous obtenons la distance par rapport à l'origine :</p>
<pre><code class="language-python">x = 3
y = 4
distance = (x**2 + y**2)**0.5  # Résultat : 5
</code></pre>
<p>Dans cet exemple, la distance entre le point <code>(3,4)</code> et l'origine <code>(0,0)</code> est de <code>5</code> unités.</p>
<h2 id="explication-du-code"><a class="header" href="#explication-du-code">Explication du code</a></h2>
<p>Ce passage de code vérifie la position d'un point par rapport à un cercle imaginaire centré sur l'origine (0, 0).</p>
<h3 id="analyse-du-point"><a class="header" href="#analyse-du-point">Analyse du point</a></h3>
<p>Si la distance du point à l'origine est inférieure ou égale à 1, cela signifie que le point est à l'intérieur du cercle. Dans ce cas, le code augmente la valeur de <code>compte_dedans</code> de 1, pour enregistrer le nombre total de points dans le cercle. Les coordonnées (x, y) du point sont ensuite enregistrées dans les listes <code>x_dans</code> et <code>y_dans</code>.</p>
<pre><code class="language-markdown">if distance &lt;= 1:
    compte_dedans += 1
    x_dans.append(x)
    y_dans.append(y)
</code></pre>
<h3 id="analyse-de-lextérieur-du-cercle"><a class="header" href="#analyse-de-lextérieur-du-cercle">Analyse de l'extérieur du cercle</a></h3>
<p>Si la distance est supérieure à 1, cela signifie que le point est à l'extérieur du cercle. Dans ce cas, les coordonnées (x, y) du point sont enregistrées dans les listes <code>x_dehors</code> et <code>y_dehors</code>.</p>
<pre><code class="language-markdown">else:
    x_dehors.append(x)
    y_dehors.append(y)
</code></pre>
<p>Dans ce contexte, une distance est généralement calculée selon la formule d'Euclide, qui est <code>distance = sqrt((x-0)^2 + (y-0)^2)</code>.</p>
<p>Le code n'est pas spécifique à un domaine particulier et pourrait être utilisé dans un large éventail d'applications, y compris la géométrie informatique et la modélisation de données.
Voici la transformation du texte en format Markdown, en suivant les directives fournies:</p>
<hr />
<h2 id="calcul-de-pi-à-laide-de-points-dans-un-cercle"><a class="header" href="#calcul-de-pi-à-laide-de-points-dans-un-cercle"><strong>Calcul de Pi à l'aide de points dans un cercle</strong></a></h2>
<p>Le calcul de la valeur de Pi peut être réalisé avec une technique impliquant l'utilisation de points à l'intérieur et à l'extérieur d'un cercle. Voici le code Python pour ce calcul:</p>
<pre><code class="language-python">pi = 4 * compte_dedans / nombre_points
</code></pre>
<ul>
<li>
<p><strong>Variables Expliqués</strong>:</p>
<ul>
<li><code>compte_dedans</code>: Représente le nombre de points se trouvant à l'intérieur du cercle.</li>
<li><code>nombre_points</code>: Correspond au nombre total de points générés, à l'intérieur et à l'extérieur du cercle.</li>
</ul>
</li>
</ul>
<p>La formule multiplie par 4 le rapport du compte de points à l’intérieur du cercle (<code>compte_dedans</code>) par rapport au nombre total de points (<code>nombre_points</code>). Cela donne une approximation du nombre Pi.</p>
<hr />
<pre><code class="language-markdown"># Résultat

Exécutez simplement la commande `print` qui est utilisée pour afficher le résultat de notre calcul.

```python
print(&quot;Pi est estimé à :&quot;, pi)
</code></pre>
<p>La phrase &quot;Pi est estimé à :&quot; est une chaîne de caractères tandis que <code>pi</code> est une variable qui contient la valeur estimée de Pi. Cette commande alors affiche le résultat sur la console.</p>
<pre><code># Code Python pour la Création d'un Graphique

Le code Python ci-dessous permet la création d'un graphique pour la visualisation des points positionnés à l'intérieur et à l'extérieur d'un cercle.

Créez un graphique en utilisant le code suivant:

</code></pre>
<pre><code class="language-python">fig, ax = plt.subplots()
ax.set_aspect('equal', 'box')
</code></pre>
<pre><code>
Dans ce code, `plt.subplots()` crée une figure (`fig`) et un ensemble d'axes (`ax`). La méthode `set_aspect()` assure que les échelles des axes x et y sont égales, garantissant que la figure représente un cercle parfait, et non une ellipse. 'equal' signifie que l'échelle est la même pour les axes x et y et 'box' assure l'égalité des ratios de l'espace utilisé pour les unités de mesure des axes x et y.
----
Voici une transformation en suivant vos directives, respectant le formatage Markdown et conservant le tableau original :

## Représentation Graphique

Pour représenter graphiquement des points qui se trouvent à la fois à l'intérieur et à l'extérieur d'un cercle, nous utilisons la fonction `scatter`. Elle permet de créer un nuage de points.

### Points à l'intérieur du cercle

```py
ax.scatter(x_dans, y_dans, color='blue', marker='.')
</code></pre>
<p>Dans cet exemple,  <code>x_dans</code> et <code>y_dans</code> désignent respectivement les coordonnées sur les axes x et y des points situés à l'intérieur du cercle. Le paramètre <code>color</code> défini à 'blue' donne la couleur des points et <code>marker</code> spécifie la forme des marqueurs. Ici, '.' représente un point.</p>
<h3 id="points-à-lextérieur-du-cercle"><a class="header" href="#points-à-lextérieur-du-cercle">Points à l'extérieur du cercle</a></h3>
<pre><code class="language-py">ax.scatter(x_dehors, y_dehors, color='red', marker='.')
</code></pre>
<p>De même, <code>x_dehors</code> et <code>y_dehors</code> désignent respectivement les coordonnées sur les axes x et y des points situés à l'extérieur du cercle. La couleur des points est définie à 'red'.</p>
<h2 id="récapitulatif"><a class="header" href="#récapitulatif">Récapitulatif</a></h2>
<p>En somme, la fonction <code>scatter</code> prend des données x et y et crée un diagramme de dispersion, avec une couleur et un marqueur particulier. Les exemples ci-dessus illustrent comment dessiner des points à l'intérieur (bleus) et à l'extérieur (rouges) d'un cercle.</p>
<h2 id="instructions-pour-lajout-dun-cercle-unité-inscrit-dans-un-carré"><a class="header" href="#instructions-pour-lajout-dun-cercle-unité-inscrit-dans-un-carré">Instructions pour l'ajout d'un cercle unité inscrit dans un carré</a></h2>
<ol>
<li>
<p><strong>Création du cercle unité</strong></p>
<p>Pour créer un cercle vert non-rempli de rayon 1 centré à l'origine (0,0), utilisez la commande suivante :</p>
<pre><code class="language-python">circle = plt.Circle((0, 0), 1, color='green', fill=False)
</code></pre>
</li>
<li>
<p><strong>Ajout du cercle sur le graphique</strong></p>
<p>Une fois le cercle créé, il doit être ajouté sur le graphique. Utilisez pour cela la commande suivante :</p>
<pre><code class="language-python">ax.add_artist(circle)
</code></pre>
</li>
</ol>
<h2 id="ces-commandes-font-appel-à-la-bibliothèque-matplotlibpyplot-ici-abrégée-plt-ainsi-quà-un-objet-axes-ici-nommé-ax-des-outils-couramment-utilisés-pour-la-création-de-graphiques-en-python-cette-méthode-permet-dajouter-efficacement-un-cercle-unité-un-cercle-de-rayon-1-à-vos-graphiques"><a class="header" href="#ces-commandes-font-appel-à-la-bibliothèque-matplotlibpyplot-ici-abrégée-plt-ainsi-quà-un-objet-axes-ici-nommé-ax-des-outils-couramment-utilisés-pour-la-création-de-graphiques-en-python-cette-méthode-permet-dajouter-efficacement-un-cercle-unité-un-cercle-de-rayon-1-à-vos-graphiques">Ces commandes font appel à la bibliothèque <code>matplotlib.pyplot</code> (ici abrégée <code>plt</code>) ainsi qu'à un objet <code>Axes</code> (ici nommé <code>ax</code>), des outils couramment utilisés pour la création de graphiques en Python. Cette méthode permet d'ajouter efficacement un cercle unité (un cercle de rayon 1) à vos graphiques.</a></h2>
<h4 id="suppression-des-introductions-"><a class="header" href="#suppression-des-introductions-">Suppression des Introductions :</a></h4>
<p>Le message a été modifié pour être plus direct en supprimant les phrases d'introduction. L'information est présentée de façon concise.</p>
<h4 id="eviter-la-redondance-"><a class="header" href="#eviter-la-redondance-">Eviter la Redondance :</a></h4>
<p>Répétitions éliminées grâce à une reformulation et une réorganisation du texte.</p>
<h4 id="présentation-claire-"><a class="header" href="#présentation-claire-">Présentation Claire :</a></h4>
<p>Les termes complexes sont expliqués brièvement. Si besoin, des exemples pertinents sont fournis.</p>
<h4 id="structure-"><a class="header" href="#structure-">Structure :</a></h4>
<p>Les idées sont décomposées en sous-sections pour faciliter la compréhension.</p>
<h4 id="langage-"><a class="header" href="#langage-">Langage :</a></h4>
<p>Le langage utilisé est simple et approprié pour un public instruit, mais non spécialisé.</p>
<hr />
<h4 id="texte-reformulé-"><a class="header" href="#texte-reformulé-">Texte Reformulé :</a></h4>
<pre><code>## Ajout de légendes aux points dans un graphique

Utilisez la fonction `legend` pour définir des légendes pour vos points sur un graphique. Par exemple :

```python
ax.legend(['Points dans le cercle','Points hors du cercle'])
</code></pre>
<p>Dans cet exemple, deux types de points sont identifiés : &quot;Points dans le cercle&quot; et &quot;Points hors du cercle&quot;.</p>
<pre><code>Voici le texte transformé comme demandé, en utilisant le formatage Markdown.

---

## Résultats et Interprétations

L'estimation de pi est de 3.136 et 3.1424 respectivement. La figure 2.3 visualise les points inter et extra circulaires pour différents nombres de points (N=1000 et N=10000 points).

La Figure 2.4 illustre les variations de pi estimées, en fonction du nombre de points. De plus, la figure 2.5 rassemble les valeurs estimatives de π, obtenues via la méthode Monte Carlo pour un nombre déterminé de points, ainsi que l'erreur relative et l'écart type.

Suite à l'analyse des résultats de simulation, nous arrivons à ces conclusions :
- À mesure qu'on augmente N, les valeurs estimées de π tendent à s'approcher de la valeur réelle, néanmoins, cela entraîne une prolongation du temps de calcul (voir Figure 2.4).
- Pour chaque nouvelle évaluation avec N constant, une nouvelle valeur estimée pour π est obtenue, due à la variabilité aléatoire (voir Tableau 2.5).
- L'aspect aléatoire de la méthode Monte Carlo nous contraint à répéter les évaluations afin d'estimer la valeur moyenne de π.

### Conclusion

Pour obtenir des résultats précis avec une incertitude acceptable, une simulation de transport d'un grand nombre de particules (au moins de 10^7) est nécessaire, pouvant s'étendre sur plusieurs jours (ref [9]).

## Utilisation de la Méthode Monte Carlo Dans Divers Domaines

Plusieurs logiciels de simulation ont été développés pour des utilisations spécifiques dans des domaines tels que la physique médicale, la médecine nucléaire ou la dosimétrie interne. Ces logiciels exploitent la méthode Monte Carlo pour le transport des particules, considérée comme la plus efficace pour estimer la répartition spatiale des particules et le dépôt d’énergie.

Les programmes Monte Carlo utilisés en médecine se répartissent en deux catégories : les programmes génériques et les programmes spécialisés.

### Programmes Monte Carlo Génériques

#### Penelope

Penelope simule le transport couplé électron-photon dans des systèmes matériels arbitraires constitués d'un certain nombre de régions homogènes limitées par des interfaces précises.

### Autres Programmes

D'autres programmes de simulations par Monte Carlo incluent EGS (Electron Gamma Shower), MCNP (Monte-Carlo Neutron Photon), PHITS, GEANT4 et des programmes spécifiques tels que SIMIND et SimSPECT.

### Processus de Simulation

La simulation du transport d’une particule par Monte Carlo se déroule en plusieurs étapes jusqu’à absorption de la particule par le milieu ou la sortie de celle-ci hors des limites de volume de simulation.

La première étape concerne la définition des dimensions et de la forme des milieux d’interactions. Trois paramètres définissent ce milieu :
- Les caractéristiques chimiques
- Les dimensions du milieu (selon les axes x, y et z)

Ces limites définissent le volume de simulation en fonction de la forme géométrique souhaitée.

## Chapitre 4. Simulation de Transport des Particules par Monte Carlo

### 4.2.2 Génération des Particules

---

# Reformulation du texte

## Graphique des particules

Le code S(x; Q; F) offre les détails concernant la particule, parmi lesquels :

- **Source (S)** : Elle génère les particules et peut se trouver à l'intérieur ou à l'extérieur du domaine de dépôt de dose.
- **Position (x)** : Il s'agit de la position initiale ou du point de départ des particules.
- **Énergie (E)** : C'est l'énergie de la particule émise par la source.
- **Cosinus directeur de la particule (cos θ)** : Détermine la direction initiale des photons par rapport à l'axe du faisceau.

## Simulation de la Particule

### Positionnement aléatoire avant la prochaine interaction (4.2.3)

La loi de Beer-Lambert détermine la distance parcourue par la particule avant la prochaine interaction grâce à l'équation T = %ln(f) (19). Les éléments impliqués sont :

- φ : un nombre aléatoire uniforme entre 0 et 1.
- Σ = coefficient d'atténuation total (en cm^{-1}).
- λ = 1/Σ : libre parcours moyen (en cm).

La prochaine position d'interaction est déterminée par $X_{i+1} =X_i + S Q$ (20), où :

- $X_i$ : est la position de la particule où l'interaction i a eu lieu.
- $X_{i+1}$ : est la position de la prochaine interaction i + 1.
- $s = λln(φ)$ : représente la distance parcourue par une particule entre deux interactions successives.
- Q : le vecteur directeur.

## Simulation de Transport Monte Carlo: Transport des Protons et Ions de Carbone

### Pouvoir d'arrêt (4.5.1)

La perte d'énergie due à l'interaction avec des électrons atomiques est calculée selon les valeurs du pouvoir d'arrêt sous forme de tableaux (équation de Bethe Bloch).

$-\\frac{dE}{dV} = \\frac{4\\pi n_m Z^2 e^4}{me^2 B^2 (4\\pi\\varepsilon_0)^2} \\ln\\left(\\frac{2 m_e c^2 \\beta^2}{I (1 - \\beta^2)}\\right)$

Où :
- ρ, p, v, c, E, dx, 2z, e, m, n, et [ sont des paramètres spécifiquement définis dans le texte.

### Diffusion (4.5.2)

La dispersion des protons est associée à la diminution de leur énergie cinétique. L'angle de diffusion à la fin de chaque étape est calculé grâce à la technique d'échantillonnage.

### Interactions nucléaires (4.5.3)

Les particules d'un faisceau ionique interagissent, générant ainsi des neutrons, des isotopes à vie courte et d'autres particules. La probabilité de ces interactions est déterminée par des données de section efficace mesurées ou des modèles nucléaires.

## PHITS Simulation Code (Chapitre 5)

PHITS (Particle and Heavy Ion Transport code System) est un logiciel de simulation de transport de particules largement utilisé. Il peut simuler le transport de neutrons, protons, ions lourds, photons et électrons sur une large gamme d'énergies.

### Structure du fichier &quot;input&quot; (Chapitre 5.2)

Le fichier &quot;input&quot; est un texte au format libre qui définit les paramètres pour la simulation, y compris le type de particules, l'énergie, la position, la direction, ainsi que les caractéristiques du matériel et de l'espace de simulation. Ses sections différentes ont des fonctions spécifiques.
</code></pre>
<h1 id="instructions-pour-lutilisation-de-la-géométrie-du-code-phits"><a class="header" href="#instructions-pour-lutilisation-de-la-géométrie-du-code-phits">Instructions pour l'Utilisation de la Géométrie du Code PHITS</a></h1>
<h2 id="structure-générale"><a class="header" href="#structure-générale">Structure Générale</a></h2>
<p>La structure générale de la géométrie du code PHITS se compose de trois sections :</p>
<ul>
<li><code>[Material]</code></li>
<li><code>[Surface]</code></li>
<li><code>[Cell]</code></li>
</ul>
<h2 id="description-des-sections"><a class="header" href="#description-des-sections">Description des Sections</a></h2>
<h3 id="la-section-material"><a class="header" href="#la-section-material">La Section <code>[Material]</code></a></h3>
<p>La section <code>[Material]</code> décrit le nombre de matériaux, le nombre d'éléments chimiques et leur proportion ou abondance. Par exemple, le nombre de matériaux H2O ou 12C.MAT [2] 12C est défini ici.</p>
<h3 id="la-section-surface"><a class="header" href="#la-section-surface">La Section <code>[Surface]</code></a></h3>
<p>La section <code>[Surface]</code> détermine le nombre et la description des surfaces qui limitent une géométrie. Ces surfaces peuvent être une sphère (notée <span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">SO</span></span></span></span>), un cylindre, un cube, etc. Par exemple :</p>
<ul>
<li><code>1 PX 2</code> : Décrit un plan perpendiculaire à l'axe OX en z = 2.</li>
<li><code>2 SO 5</code> : Décrit une sphère centrée, de rayon 5cm.</li>
</ul>
<p><code>CHAPITRE 5. SIMULATION PAR LE CODE PHITS</code></p>
<div class="table-wrapper"><table><thead><tr><th>Élément</th><th>Symbole de Surface</th><th>Type</th><th>Explication</th><th>Équation</th><th>Paramètres</th></tr></thead><tbody>
<tr><td>Plane</td><td>P</td><td>Multi-usage</td><td><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.7667em;vertical-align:-0.0833em;"></span><span class="mord mathnormal">A</span><span class="mord mathnormal">x</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.8778em;vertical-align:-0.1944em;"></span><span class="mord mathnormal" style="margin-right:0.05017em;">B</span><span class="mord mathnormal" style="margin-right:0.03588em;">y</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.7667em;vertical-align:-0.0833em;"></span><span class="mord mathnormal" style="margin-right:0.07153em;">C</span><span class="mord mathnormal" style="margin-right:0.04398em;">z</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">0</span></span></span></span></td><td>A, B, C, D</td><td></td></tr>
<tr><td>Vertical w/ X-axis</td><td>PX</td><td><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6667em;vertical-align:-0.0833em;"></span><span class="mord mathnormal">x</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">0</span></span></span></span></td><td>D</td><td></td><td></td></tr>
<tr><td>Vertical w/ Y-axis</td><td>PY</td><td><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.7778em;vertical-align:-0.1944em;"></span><span class="mord mathnormal" style="margin-right:0.03588em;">y</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">0</span></span></span></span></td><td>D</td><td></td><td></td></tr>
<tr><td>Vertical w/ Z-axis</td><td>PZ</td><td><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6667em;vertical-align:-0.0833em;"></span><span class="mord mathnormal" style="margin-right:0.04398em;">z</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">0</span></span></span></span></td><td>D</td><td></td><td></td></tr>
<tr><td>Sphere, Origin at Center</td><td>SO</td><td><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8974em;vertical-align:-0.0833em;"></span><span class="mord"><span class="mord mathnormal">x</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8141em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:1.0085em;vertical-align:-0.1944em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.03588em;">y</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8141em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.8974em;vertical-align:-0.0833em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.04398em;">z</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8141em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">−</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.8141em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.00773em;">R</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.8141em;"><span style="top:-3.063em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight">2</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2778em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">0</span></span></span></span></td><td>R</td><td></td><td></td></tr>
</tbody></table>
</div>
<h3 id="la-section-cell"><a class="header" href="#la-section-cell">La Section <code>[Cell]</code></a></h3>
<p>La section <code>[Cell]</code> donne les cellules qui sont définies par les surfaces et les matériaux décrits dans les sections <code>[Surface]</code> et <code>[Material]</code> respectivement.</p>
<p>Exemple :</p>
<ul>
<li><code>100 1 -1.01 -2</code>: Une cellule nommée &quot;100&quot;, remplie du matériau 1 (ici H2O), de densité 1.01 g/cm³ et prenant la forme de la surface donnée dans la section [Surface] (ici une sphère).</li>
</ul>
<h3 id="les-tallies"><a class="header" href="#les-tallies">Les Tallies</a></h3>
<p>Les tallies implémentés dans le code PHITS peuvent être utilisés pour obtenir des informations sur la géométrie et calculer des quantités physiques comme par exemple la fluence, les énergies déposées (chaleur) ou le volume.</p>
<h3 id="la-libraire-de-données-nucléaires-jendl-40"><a class="header" href="#la-libraire-de-données-nucléaires-jendl-40">La Libraire de Données Nucléaires JENDL-4.0</a></h3>
<p>Cette libraire est utilisée pour le calcul du transport des neutrons de moins de 20 MeV et des émissions de particules secondaires induites par ces neutrons.</p>
<h3 id="les-modèles-physiques-dans-phits"><a class="header" href="#les-modèles-physiques-dans-phits">Les Modèles Physiques dans PHITS</a></h3>
<p>PHITS intègre de nombreux modèles physiques pour simuler le transport de différentes particules sur une large gamme d'énergie :</p>
<ul>
<li><strong>JAM et INCL4.6:</strong> Modèle de cascade hadronique pour simuluer les réactions nucléaires induites par les hadrons.</li>
<li><strong>Modèle JQMD (JAERI Quantum Molecular Dynamics):</strong> Pour simuler les réactions induites par des ions lourds d'énergie inférieure à 3,5GeV/nucléon.</li>
<li><strong>Modèle SMM (Statistical Multi-fragmentation Model):</strong> Pour simuler les réactions de fragmentation.</li>
<li><strong>Modèle GEM (Generalized Evaporation Model):</strong> Utilisé pour estimer précisément les spectres de radiations et les taux de production d'isotopes.</li>
<li><strong>Modèle INCL 4.6 (Intra-nuclear cascade of Liege):</strong> Utilisé pour simuler le transport des neutrons plus énergétiques.</li>
</ul>
<h3 id="arrêt-de-la-simulation"><a class="header" href="#arrêt-de-la-simulation">Arrêt de la Simulation</a></h3>
<p>La simulation sera arrêtée en utilisant la directive <code>[END]</code>.</p>
<pre><code># Simulations de Transport de Particules

L'étude présentée ici repose sur l'utilisation de l'algorithme EGS5, qui simule les interactions atomiques des électrons, des positrons et des photons. Cette mise en œuvre améliore la précision de la simulation du transport d'électrons, particulièrement pour les énergies plus faibles. C'est essentiel pour certaines applications de physique médicale[^29^].

## Matériels et Méthodes

Dans cette étude, nous utilisons le code PHITS pour simuler le transport des particules utilisées en hadronthérapie (proton, 12C, neutron...). Nous déterminons ensuite les caractéristiques balistiques des protons et des ions de carbone 12 tout en suivant les particules secondaires qui contribuent à la déposition de dose.

Nous avons commencé par créer un &quot;fantôme&quot; parallélépipédique de dimensions 20 cm x 20 cm x 40 cm. Puis, une source de faisceau cylindrique de protons de diamètre 8 cm et d'énergie E_y = 140 MeV est mise en place. Le matériau d'étude est de l'eau, avec une densité de p=1 g/cm³. Du polyéthylène, C2H4, est également inclus dans la simulation pour la validation.

## Résultats de la Simulation

Les résultats de la simulation sont en accord avec les résultats expérimentaux, avec une légère différence observable au niveau du pic. Cette différence pourrait être due à divers paramètres, comme le pas de simulation. Un &quot;pas&quot; plus petit entraîne plus de collisions, et donc une dose déposée plus importante.

### Figures de Résultats

- Figure 6.3.b montre les fluctuations importantes constatées lorsque le nombre de particules est faible.
- Figure 6.4 présente la distribution de dose autour du faisceau incident dans le plan xz, avec des valeurs maximales représentées en rouge et minimales en bleu.
- Figure 6.5 montre les régions où les particules primaires et secondaires sont les plus nombreuses autour du faisceau primaire.
- Figure 6.8 illustre l'effet de l'augmentation de l'énergie des particules primaires sur la profondeur de pénétration des protons dans le fantôme.

Les collisions engendrent des particules secondaires: neutrons, photons, électrons, etc. Ces particules secondaires contribuent à une faible dose d'environ 0,01% de la dose totale déposée avant et au pic de Bragg. Les neutrons et les photons déposent une dose après le pic de Bragg.

## Discussion

Nous constatons que lorsque la profondeur dans l'eau augmente, la largeur à mi-hauteur elle aussi augmente, indiquant une dispersion du faisceau de protons ainsi qu'une perte de la précision du dépôt de dose avec la profondeur (Voir tableau 6.1).

Après cela, une simulation de transport d'ions Carbone 12 est effectuée avec une source d'ions de Carbone 12 de 264 MeV (Voir Tableau 6.2). La figure 6.9 générée par le logiciel PHITS montre que les ions de carbone primaires sont responsables d'environ 93% de la dose déposée à hauteur dans le fantôme avant et au pic de Bragg.

[^29^]: Référence à l'œuvre citée.
## Résumé des résultats

Le Tableau 6.3 montre les données de largeur à mi-hauteur et la dispersion en profondeur pour deux ions différents. Il suggère que les faisceaux de protons ont une précision de dépôt de dose inférieure à celle des ions carbone, et que les ions carbone ont une moindre dispersion en profondeur comparé aux protons.

### Simulation de la distribution de dose

La Figure 6.12, obtenue via le logiciel PHITS, montre la distribution de dose en profondeur d'ions carbone (E=400 MeV/u) et des ions néon (E=560 MeV). Les résultats révèlent que la dose déposée par les ions carbone avant le pic de Bragg est presque constante et plus faible que celle des ions de néon. Après le pic, la queue de fragmentation des ions néon est plus importante que celle des ions carbone, mais la dispersion en profondeur est similaire pour les deux ions.

Dans le tableau 6.3, nous avons calculé le taux de dose en relation avec celle déposée au pic de Bragg à l'entrée (z=0 cm) et juste après le pic (à z=27,6 cm) du fantôme.

| Ions  | Taux de dose pour z =0 cm  | Taux de dose pour z = 27,6 cm |
|-------|---------------------------|-------------------------------|
| Nt    | 0,35                      | 0,18                          |
| Lot   | 0,23                      | 0,091                         |

*Tableau 6.4 - Taux de dose par rapport au pic de Bragg pour les ions de carbone et ions de néon*

### Phénomène de fragmentation

La fragmentation est définie comme la décomposition d’un noyau en noyaux légers et d'autres particules.

## Conclusion et discussion

Les ions de carbone 12 et les protons déposent une quantité d'énergie modérée et presque constante au départ, atteignant un maximum en fin de parcours. Cette propriété, combinée à une faible dispersion en profondeur et latéralement, permet d'irradier précisément le volume cible pour détruire les tumeurs tout en protégeant les organes sains. Les ions se révèlent ainsi plus efficaces que les électrons et les rayons X pour ce type de traitement, avec les ions carbone surpassant les protons.

Ce travail a d'abord examiné l'interaction des particules avec la matière, un concept clé pour comprendre le transport et le transfert d'énergie d'une particule dans un milieu biologique. En utilisant la méthode de Monte-Carlo, nous avons comparé le dépôt d'énergie dans l'eau par un faisceau de protons et un d'ions carbone. Nos observations confirment leur performance comparable en fin de cours, visible par le pic de Bragg.

En conclusion, bien que nous ayons rencontré des défis techniques tels que le besoin d'un grand nombre de particules pour une estimation précise par Monte Carlo, et la difficulté d’avoir à maîtriser un code de simulation, ces résultats offrent des perspectives pour améliorer notre compréhension du comportement des ions dans un milieu biologique, étudier les fragments produits et leurs propriétés, et améliorer les moyens de radioprotection contre les particules secondaires.
</code></pre>

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                            <a rel="prev" href="004.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>

                            <a rel="next" href="006.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>

                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                    <a rel="prev" href="004.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>

                    <a rel="next" href="006.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
            </nav>

        </div>




        <script>
            window.playground_copyable = true;
        </script>


        <script src="elasticlunr.min.js"></script>
        <script src="mark.min.js"></script>
        <script src="searcher.js"></script>

        <script src="clipboard.min.js"></script>
        <script src="highlight.js"></script>
        <script src="book.js"></script>

        <!-- Custom JS scripts -->
        <script src="./theme/tabbed-code-blocks.js"></script>
        <script src="./theme/highlight.css"></script>


    </div>
    </body>
</html>
