#!/bin/bash
# shellcheck disable=2016


main(){
  file="${1:-}"
  if [ -z "$file" ];then
    echo "the is no file provided" 
    exit 1
  fi

  if [ ! -e "$file" ];then
    echo "the is no file exist called $file" 
    exit 1
  fi

  case "$file" in
      *.pdf) 
          name="${file##*/}"
          name="${name%.pdf}"
          output="./src/${name}.md"
          summary_output="./${name}.md"
          if [ -e "$output" ];then
            output="./src/${name}-$(date +%Y-%m-%d-%H_%M).md"
            summary_output="./${name}-$(date +%Y-%m-%d-%H_%M).md"
          fi
          ;;
      *)
          echo "File has an unsupported extension"
          exit 1
          ;;
  esac

  cmd=""

  lang=$(select_language)

  tasks=('Ocr to correcte text' 'Paraphrase text for beginner' 'Ocr then paraphrase' 'pass')
  selected_tasks=()
  need_more_task=true
  default_option=3

  while $need_more_task; do
    clear
    if [ ${#tasks[@]} -le 1 ]; then
      break
    fi

    echo "Available tasks:" >&2
    for ((i = 0; i < ${#tasks[@]}; i++)); do
      echo "$((i + 1))) ${tasks[i]}" >&2
    done

    read -rp "Enter the task number to add (default is $default_option): " choice
    clear
    if [ -z "$choice" ]; then
      if [ $default_option -eq 3 ];then
        choice=3
        default_option=4
      else
        choice=4
      fi
    elif [ "$choice" -eq 4 ] && [ "$default_option" -eq 3 ];then
      continue
    fi
    if ((choice >= 1 && choice <= ${#tasks[@]})); then
      task_index=$((choice - 1))
      case ${tasks[task_index]} in
        'Ocr to correcte text')
          selected_tasks+=('--llm correct_ocr ')
          ;;
        'Paraphrase text for beginner')
          selected_tasks+=('--llm paraphrasing ')
          ;;
        'Ocr then paraphrase')
          selected_tasks+=('--llm correct_ocr ' '--llm paraphrasing ')
          unset 'tasks[task_index]'
          break
          ;;
        'pass')
          unset 'tasks[task_index]'
          break
          ;;
      esac
      unset 'tasks[task_index]'
      tasks=("${tasks[@]}")  # Re-index the array
    else
      echo "Invalid task number." >&2
    fi
    clear
  done

  printf "%s" "${selected_tasks[@]}"

  task=$(printf "%s" "${selected_tasks[@]}")
  # echo "$task"
  
  # exit 1
  clear
  
  cmd=''
  cmd+='#!/bin/bash\n\n'
  cmd+='\n'
  cmd+='if ! python3 llmtask.py                \\\n'
  cmd+='    --ocr /usr/bin/tesseract           \\\n'
  cmd+="    --lang $lang                          \\\\\n"
  cmd+="    $task \\\\\n"
  cmd+="    --file $file \\\\\n"
  cmd+="    1>$output\n"
  cmd+='then\n'
  cmd+='    echo "some errors"\n'
  cmd+='    exit 1\n'
  cmd+='fi\n\n'
  cmd+="echo '- [${name}](${summary_output})' >> ./src/SUMMARY.md"
  
  echo -e "$cmd" > ./convert.sh
}

remove_task() {
  local task_option="$1"
  index=0
  for i in "${!tasks[@]}"; do
    if [[ "${tasks[i]}" == "$task_option" ]]; then
      index=$i
      break
    fi
  done
  unset "tasks[$index]"
  tasks=("${tasks[@]}")  # Remove empty placeholders
}

select_language() {
  langs=('English' 'French')
  default_option=1

  echo "Select a language (default is English):" >&2
  for ((i=0; i<${#langs[@]}; i++)); do
    echo "$((i+1))) ${langs[i]}" >&2
  done

  read -rp "Enter your choice (default is $default_option): " choice >&2

  if [ -z "$choice" ]; then
    choice=$default_option
  fi

  case $choice in
    1)
      echo 'en'
      ;;
    2)
      echo 'fr'
      ;;
    *)
      echo 'en'
      ;;
  esac
}

clear

main "$@"
