name: Deploy mdBook site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    environment: # specify the name of the environment that contains the secret
      name: my-environment
    
    # concurrency:
    #   group: "pages"
    #   cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook -p
          curl -sSL $url | tar -xz --directory=./mdbook

          tag=$(curl 'https://api.github.com/repos/lzanini/mdbook-katex/releases/latest' | jq -r '.tag_name')
          url="https://github.com/lzanini/mdbook-katex/releases/download/${tag}/mdbook-katex-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook -p
          curl -sSL $url | tar -xz --directory=./mdbook

          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build Book
        run: |
          mdbook build
          echo "pwd"
          pwd
          echo "ls"
          ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

