name: PDF to Markdown

on:
  push:
    paths:
      - 'PDFs/*.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    environment: # specify the name of the environment that contains the secret
      name: my-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-ara tesseract-ocr-fra
          pip install -r requirements.txt
      - name: Get changed PDF file name
        run: |
          FILE=$(jq -r '.commits[0].added[0]' $GITHUB_EVENT_PATH)
          # echo "FILE=$FILE" >> $GITHUB_ENV
          export FILE=$FILE
      - name: Convert PDF to Markdown
        env: # pass the secret as an environment variable to the script
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo python pdf_to_paraphrase.py $FILE --ocr /usr/bin/tesseract \> src/$FILE.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: init
          branch: master
          file_pattern: src/$FILE.md
