name: PDF to Markdown

on:
  push:
    paths:
      - 'En_PDFs/*.pdf'
      - 'Fr_PDFs/*.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    environment: # specify the name of the environment that contains the secret
      name: my-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo sudo apt update
          echo sudo apt install -y poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-ara tesseract-ocr-fra
          echo pip install -r requirements.txt
          echo pip install pptgpt-0.1.8-py3-none-any.whl -qq --ignore-installed blinker
      - name: Get changed PDF file name
        run: |
          #cat $GITHUB_EVENT_PATH
          du -h -d0 .
          HASH=$(jq -r '.commits[0].id' $GITHUB_EVENT_PATH)
          FILE="$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$HASH | jq -r '.files[] | select(.status == "added") | .filename' | grep pdf | head -1)"
          echo "FILE=$FILE"
          echo "FILE=$FILE" >> $GITHUB_ENV
      - name: Convert PDF to Markdown
        env: # pass the secret as an environment variable to the script
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          OUTPUT="${FILE#PDFs/}"
          OUTPUT="src/${OUTPUT%.pdf}.md"
          LANG="${FILE%_PDFs/*}"
          echo "OPENAI_API_KEY=$OPENAI_API_KEY"
          echo "FILE=$FILE"
          echo "OUTPUT=$OUTPUT"
          echo "LANG=$LANG"

          mkdir -p src/

          #python pdf_to_paraphrase.py "$FILE" --ocr /usr/bin/tesseract > "$OUTPUT" && rm -f "$FILE"
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: init
          branch: master
          #file_pattern: src/*.md
