name: PDF to Markdown

on:
  push:
    paths:
      - 'convert.sh'

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    environment: # specify the name of the environment that contains the secret
      name: my-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y poppler-utils tesseract-ocr tesseract-ocr-eng tesseract-ocr-ara tesseract-ocr-fra 1>/dev/null
          pip install -r requirements.txt 1>/dev/null
          pip install pptgpt-0.1.8-py3-none-any.whl -qq --ignore-installed blinker 1>/dev/null

      #1- name: Get changed PDF file name
      #1  run: |
      #1    #cat $GITHUB_EVENT_PATH
      #1    du -h -d0 .
      #1    jq . $GITHUB_EVENT_PATH

      #1    HASH0=$(jq -r '.commits[0].id' $GITHUB_EVENT_PATH)
      #1    HASH1=$(jq -r '.commits[1].id' $GITHUB_EVENT_PATH)
      #1    echo "HASH0:$HASH0"
      #1    echo "HASH1:$HASH1"
      #1    #TODO while not empty
      #1    curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$HASH0 > hash0.json
      #1    curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$HASH1 > hash1.json
      #1    FILE="$( jq -r '.files[] | select(.status == "added") | .filename'  hash0.json | grep pdf | head -1)"
      #1    [ -z "$FILE" ] && FILE="$( jq -r '.files[] | select(.status == "added") | .filename'  hash1.json | grep pdf | head -1)"
      #1    echo "FILE=$FILE"
      #1    echo "FILE=$FILE" >> $GITHUB_ENV

      #1    # assert faield if no FILE=null
      #1    echo "ls $FILE"
      #1    ls "$FILE"

      - name: Convert PDF to Markdown
        env: # pass the secret as an environment variable to the script
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "mkdir -p ./src/"
          mkdir -p ./src/
          echo "cat -n ./convert.sh"
          cat -n ./convert.sh
          echo "bash ./convert.sh"
          bash ./convert.sh
          git add ./src/*.md
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: init
          branch: master
          skip_fetch: false
          skip_checkout: false
          push_options: --force
          commit_options: --no-verify
      # - name: Test if the Conversion is done
      #   run: |
      #     [ $CONVERSION ] && echo conversion is Done || exit 1
      # # ----------------------------------------------------------------------
      # # ----------------------------------------------------------------------
      # # ----------------------------------------------------------------------


  # deploy:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write  # To push a branch 
  #     pages: write  # To push to a GitHub Pages site
  #     id-token: write # To update the deployment status
  #   environment: # specify the name of the environment that contains the secret
  #     name: my-environment
  #   steps:
  #     - uses: actions/checkout@v3
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook -p
          curl -sSL $url | tar -xz --directory=./mdbook

          tag=$(curl 'https://api.github.com/repos/lzanini/mdbook-katex/releases/latest' | jq -r '.tag_name')
          url="https://github.com/lzanini/mdbook-katex/releases/download/${tag}/mdbook-katex-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook -p
          curl -sSL $url | tar -xz --directory=./mdbook

          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build Book
        run: |
          echo "mdbook build"
          mdbook build
          echo "cat ./src/SUMMARY.md"
          cat ./src/SUMMARY.md
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
